window.LTC_SPECIES_CHUNKS = window.LTC_SPECIES_CHUNKS || {};
window.LTC_SPECIES_CHUNKS["Puffers"] = [
  {
    "id": "valentini-puffer",
    "name": "Valentini Puffer",
    "aliases": [
      "Saddled Toby",
      "Black Saddle Puffer"
    ],
    "scientific": "Canthigaster valentini",
    "category": "Puffers",
    "type": "Saltwater Fish",
    "price": 0,
    "stockSize": "",
    "maxSize": "4 in",
    "minTank": "30+ gal",
    "careLabel": "Easy",
    "diet": "Omnivore",
    "origin": "Indo-Pacific",
    "habitat": "Coral reef slopes and lagoons",
    "tankCode": "",
    "aggression": 30,
    "coralRisk": 28,
    "invertRisk": 32,
    "careDifficulty": 24,
    "role": "Tiny curious puffer with big personality",
    "visualCue": "Cream body with four dark saddle-shaped patches and orange-tan coloring on the back. Small beak-like mouth.",
    "overview": "A tiny puffer with enormous personality. Constantly curious, investigating everything in the tank with its beady eyes. Not truly reef safe as it may nip corals and eat small invertebrates.",
    "facts": [
      "Personality is the main selling point — watches you back through the glass.",
      "Will nip at corals, clams, and small invertebrates.",
      "The beak can deliver a painful bite — handle carefully."
    ],
    "bestWith": [
      "Fish-only or FOWLR tanks",
      "Owners wanting maximum personality",
      "Medium-sized communities"
    ],
    "cautionWith": [
      "Reef tanks with prized corals or clams",
      "Small ornamental shrimp",
      "Handling with bare hands"
    ],
    "staffNote": "Pure personality fish. Customers fall in love watching it investigate the tank.",
    "photoTitle": "Canthigaster valentini",
    "inStock": false,
    "badges": [],
    "water": {
      "ph_low": 8,
      "ph_high": 8.4,
      "sal_low": 1.024,
      "sal_high": 1.026,
      "temp_low": 75,
      "temp_high": 80
    },
    "name_es": "Puffer Valentini",
    "overview_es": "Un puffer diminuto con personalidad enorme. Constantemente curioso, investigando todo con sus ojos.",
    "role_es": "Puffer diminuto y curioso con gran personalidad",
    "diet_es": "Omnívoro",
    "origin_es": "Indo-Pacífico",
    "headerSummary": "Tiny curious puffer with big personality. Look for cream body with four dark saddle-shaped patches and orange-tan coloring on the back. Small beak-like mouth. Plan on at least 30+ gal.",
    "seasonal": null
  },
  {
    "id": "blue-spot-puffer",
    "name": "Blue Spot Puffer",
    "name_es": "Blue Spot Puffer",
    "aliases": [],
    "scientific": "Canthigaster solandri",
    "category": "Puffers",
    "type": "Saltwater Fish",
    "price": 0,
    "stockSize": "",
    "maxSize": "5 in",
    "minTank": "30+ gal",
    "diet": "Omnivore",
    "diet_es": "",
    "origin": "Unknown",
    "origin_es": "",
    "habitat": "Reef / rocky",
    "tankCode": "",
    "aggression": 38,
    "coralRisk": 78,
    "invertRisk": 20,
    "careDifficulty": 56,
    "role": "Interactive puffer profile with beak care and invertebrate compatibility trade-offs",
    "role_es": "",
    "overview": "Blue Spot Puffer is an interactive puffer sale where personality, beak care, and invert safety all matter. The catalog lists a minimum tank around 30+ gal. Adult size is listed around 5 in. Diet here is listed as Omnivore.",
    "overview_es": "",
    "facts": [
      "Adult size in this catalog is listed around 5 in.",
      "Plan around roughly 30+ gal or larger for long-term care.",
      "Diet in this catalog: Omnivore."
    ],
    "photoTitle": "Blue Spot Puffer",
    "inStock": false,
    "badges": [],
    "water": {
      "ph_low": 8,
      "ph_high": 8.4,
      "sal_low": 1.024,
      "sal_high": 1.026,
      "temp_low": 75,
      "temp_high": 80
    },
    "seasonal": null,
    "careLabel": "Intermediate",
    "visualCue": "Look for the rounded puffer body, beak-like mouth, and curious, interactive swimming style.",
    "bestWith": [
      "Mature systems that meet the minimum tank size",
      "Fish-only or mixed systems built around assertive livestock",
      "Semi-aggressive tankmates of similar size"
    ],
    "cautionWith": [
      "Tankmates that do not match its adult size or activity level",
      "Corals or polyps that could be nipped or disturbed"
    ],
    "staffNote": "",
    "headerSummary": "Interactive puffer profile with beak care and invertebrate compatibility trade-offs. Plan on roughly 30+ gal or larger long term.",
    "behavior": "Curious, alert, and always investigating rockwork and equipment. Often one of the most interactive fish in the tank.",
    "feedingNotes": "Offer varied prepared foods plus harder meaty items now and then to help keep the beak worn down.",
    "recognitionNotes": "Small puffer body, quick turns, and blue spotting over a lighter body color.",
    "buyingGuidance": "Best sold to buyers who want puffer personality and already accept the trade-off with shrimp, snails, and possible coral nipping."
  },
  {
    "id": "camel-cowfish",
    "name": "Camel Cowfish",
    "name_es": "Camel Cowfish",
    "aliases": [],
    "scientific": "Tetrosomus gibbosus",
    "category": "Puffers",
    "type": "Saltwater Fish",
    "price": 0,
    "stockSize": "",
    "maxSize": "20 in",
    "minTank": "125+ gal",
    "diet": "Omnivore",
    "diet_es": "",
    "origin": "Unknown",
    "origin_es": "",
    "habitat": "Reef / rocky",
    "tankCode": "",
    "aggression": 38,
    "coralRisk": 78,
    "invertRisk": 20,
    "careDifficulty": 56,
    "role": "Interactive puffer profile with beak care and invertebrate compatibility trade-offs",
    "role_es": "",
    "overview": "Camel Cowfish is an interactive puffer sale where personality, beak care, and invert safety all matter. The catalog lists a minimum tank around 125+ gal. Adult size is listed around 20 in. Diet here is listed as Omnivore.",
    "overview_es": "",
    "facts": [
      "Adult size in this catalog is listed around 20 in.",
      "Plan around roughly 125+ gal or larger for long-term care.",
      "Diet in this catalog: Omnivore."
    ],
    "photoTitle": "Camel Cowfish",
    "inStock": false,
    "badges": [],
    "water": {
      "ph_low": 8,
      "ph_high": 8.4,
      "sal_low": 1.024,
      "sal_high": 1.026,
      "temp_low": 75,
      "temp_high": 80
    },
    "seasonal": null,
    "careLabel": "Intermediate",
    "visualCue": "Look for the rounded puffer body, beak-like mouth, and curious, interactive swimming style.",
    "bestWith": [
      "Mature systems that meet the minimum tank size",
      "Fish-only or mixed systems built around assertive livestock",
      "Semi-aggressive tankmates of similar size"
    ],
    "cautionWith": [
      "Tankmates that do not match its adult size or activity level",
      "Corals or polyps that could be nipped or disturbed"
    ],
    "staffNote": "",
    "headerSummary": "Interactive puffer profile with beak care and invertebrate compatibility trade-offs. Plan on roughly 125+ gal or larger long term.",
    "behavior": "Usually calm and oddly graceful rather than aggressive, but easily stressed by rough companions and chaotic tank layouts.",
    "feedingNotes": "Feed a varied omnivore routine with mixed meaty foods and vegetable content while keeping water quality very stable.",
    "recognitionNotes": "Nothing else in the tank moves or looks quite like a cowfish.",
    "buyingGuidance": "Sell as an advanced oddball, not a cute novelty fish. The right buyer already understands stress sensitivity, adult size, and the need for a calm stable system."
  },
  {
    "id": "dogface-puffer",
    "name": "Dogface Puffer",
    "name_es": "Dogface Puffer",
    "aliases": [],
    "scientific": "Arothron nigropunctatus",
    "category": "Puffers",
    "type": "Saltwater Fish",
    "price": 0,
    "stockSize": "",
    "maxSize": "13 in",
    "minTank": "125+ gal",
    "diet": "Carnivore",
    "diet_es": "",
    "origin": "Unknown",
    "origin_es": "",
    "habitat": "Reef / rocky",
    "tankCode": "",
    "aggression": 38,
    "coralRisk": 78,
    "invertRisk": 20,
    "careDifficulty": 56,
    "role": "Interactive puffer profile with beak care and invertebrate compatibility trade-offs",
    "role_es": "",
    "overview": "Dogface Puffer is an interactive puffer sale where personality, beak care, and invert safety all matter. The catalog lists a minimum tank around 125+ gal. Adult size is listed around 13 in. Diet here is listed as Carnivore.",
    "overview_es": "",
    "facts": [
      "Adult size in this catalog is listed around 13 in.",
      "Plan around roughly 125+ gal or larger for long-term care.",
      "Diet in this catalog: Carnivore."
    ],
    "photoTitle": "Dogface Puffer",
    "inStock": false,
    "badges": [],
    "water": {
      "ph_low": 8,
      "ph_high": 8.4,
      "sal_low": 1.024,
      "sal_high": 1.026,
      "temp_low": 75,
      "temp_high": 80
    },
    "seasonal": null,
    "careLabel": "Intermediate",
    "visualCue": "Look for the rounded puffer body, beak-like mouth, and curious, interactive swimming style.",
    "bestWith": [
      "Mature systems that meet the minimum tank size",
      "Fish-only or mixed systems built around assertive livestock",
      "Semi-aggressive tankmates of similar size"
    ],
    "cautionWith": [
      "Tankmates that do not match its adult size or activity level",
      "Corals or polyps that could be nipped or disturbed"
    ],
    "staffNote": "",
    "headerSummary": "Interactive puffer profile with beak care and invertebrate compatibility trade-offs. Plan on roughly 125+ gal or larger long term.",
    "behavior": "Interactive, food-driven, and often immediately aware of the person standing in front of the tank.",
    "feedingNotes": "Feed a varied carnivore diet with shell-on foods to help control beak growth and support long-term feeding success.",
    "recognitionNotes": "The face is the appeal: expressive eyes, blunt snout, and dog-like look.",
    "buyingGuidance": "Excellent for buyers who want personality in a large fish-only system. Poor fit for reef buyers who expect shrimp, snails, or delicate corals to survive unchanged."
  },
  {
    "id": "longhorn-cowfish",
    "name": "Longhorn Cowfish",
    "name_es": "Longhorn Cowfish",
    "aliases": [],
    "scientific": "Lactoria cornuta",
    "category": "Puffers",
    "type": "Saltwater Fish",
    "price": 0,
    "stockSize": "",
    "maxSize": "20 in",
    "minTank": "180+ gal",
    "diet": "Omnivore",
    "diet_es": "",
    "origin": "Unknown",
    "origin_es": "",
    "habitat": "Reef / rocky",
    "tankCode": "",
    "aggression": 38,
    "coralRisk": 78,
    "invertRisk": 20,
    "careDifficulty": 56,
    "role": "Interactive puffer profile with beak care and invertebrate compatibility trade-offs",
    "role_es": "",
    "overview": "Longhorn Cowfish is an interactive puffer sale where personality, beak care, and invert safety all matter. The catalog lists a minimum tank around 180+ gal. Adult size is listed around 20 in. Diet here is listed as Omnivore.",
    "overview_es": "",
    "facts": [
      "Adult size in this catalog is listed around 20 in.",
      "Plan around roughly 180+ gal or larger for long-term care.",
      "Diet in this catalog: Omnivore."
    ],
    "photoTitle": "Longhorn Cowfish",
    "inStock": false,
    "badges": [],
    "water": {
      "ph_low": 8,
      "ph_high": 8.4,
      "sal_low": 1.024,
      "sal_high": 1.026,
      "temp_low": 75,
      "temp_high": 80
    },
    "seasonal": null,
    "careLabel": "Intermediate",
    "visualCue": "Look for the rounded puffer body, beak-like mouth, and curious, interactive swimming style.",
    "bestWith": [
      "Mature systems that meet the minimum tank size",
      "Fish-only or mixed systems built around assertive livestock",
      "Semi-aggressive tankmates of similar size"
    ],
    "cautionWith": [
      "Tankmates that do not match its adult size or activity level",
      "Corals or polyps that could be nipped or disturbed"
    ],
    "staffNote": "",
    "headerSummary": "Interactive puffer profile with beak care and invertebrate compatibility trade-offs. Plan on roughly 180+ gal or larger long term.",
    "behavior": "Usually calm and slow rather than confrontational, but easily stressed by fast aggressive fish.",
    "feedingNotes": "Feed a varied omnivore diet and protect water quality; the husbandry challenge is usually the system, not just the menu.",
    "recognitionNotes": "The horns and box-shaped body make this fish unmistakable.",
    "buyingGuidance": "This should be sold as a dedicated oddball project fish, not as a novelty add-on to a busy community tank."
  },
  {
    "id": "porcupine-puffer",
    "name": "Porcupine Puffer",
    "name_es": "Porcupine Puffer",
    "aliases": [],
    "scientific": "Diodon holocanthus",
    "category": "Puffers",
    "type": "Saltwater Fish",
    "price": 0,
    "stockSize": "",
    "maxSize": "20 in",
    "minTank": "180+ gal",
    "diet": "Carnivore",
    "diet_es": "",
    "origin": "Unknown",
    "origin_es": "",
    "habitat": "Reef / rocky",
    "tankCode": "",
    "aggression": 38,
    "coralRisk": 78,
    "invertRisk": 20,
    "careDifficulty": 56,
    "role": "Interactive puffer profile with beak care and invertebrate compatibility trade-offs",
    "role_es": "",
    "overview": "Porcupine Puffer is an interactive puffer sale where personality, beak care, and invert safety all matter. The catalog lists a minimum tank around 180+ gal. Adult size is listed around 20 in. Diet here is listed as Carnivore.",
    "overview_es": "",
    "facts": [
      "Adult size in this catalog is listed around 20 in.",
      "Plan around roughly 180+ gal or larger for long-term care.",
      "Diet in this catalog: Carnivore."
    ],
    "photoTitle": "Porcupine Puffer",
    "inStock": false,
    "badges": [],
    "water": {
      "ph_low": 8,
      "ph_high": 8.4,
      "sal_low": 1.024,
      "sal_high": 1.026,
      "temp_low": 75,
      "temp_high": 80
    },
    "seasonal": null,
    "careLabel": "Intermediate",
    "visualCue": "Look for the rounded puffer body, beak-like mouth, and curious, interactive swimming style.",
    "bestWith": [
      "Mature systems that meet the minimum tank size",
      "Fish-only or mixed systems built around assertive livestock",
      "Semi-aggressive tankmates of similar size"
    ],
    "cautionWith": [
      "Tankmates that do not match its adult size or activity level",
      "Corals or polyps that could be nipped or disturbed"
    ],
    "staffNote": "",
    "headerSummary": "Interactive puffer profile with beak care and invertebrate compatibility trade-offs. Plan on roughly 180+ gal or larger long term.",
    "behavior": "Usually interactive and bold, often becoming one of the most outgoing fish in the room.",
    "feedingNotes": "Feed a varied carnivore diet with hard-shelled foods regularly so the beak stays manageable.",
    "recognitionNotes": "Spot pattern, visible spines, and very obvious face make identification easy.",
    "buyingGuidance": "Great for the right big predator display, bad for a reef buyer who just wants a cute puffer. Sell the adult fish, not the juvenile look."
  },
  {
    "id": "saddle-valentini-puffer",
    "name": "Saddle Valentini Puffer",
    "name_es": "Saddle Valentini Puffer",
    "aliases": [],
    "scientific": "Canthigaster valentini",
    "category": "Puffers",
    "type": "Saltwater Fish",
    "price": 0,
    "stockSize": "",
    "maxSize": "4 in",
    "minTank": "30+ gal",
    "diet": "Omnivore",
    "diet_es": "",
    "origin": "Unknown",
    "origin_es": "",
    "habitat": "Reef / rocky",
    "tankCode": "",
    "aggression": 38,
    "coralRisk": 78,
    "invertRisk": 20,
    "careDifficulty": 56,
    "role": "Interactive puffer profile with beak care and invertebrate compatibility trade-offs",
    "role_es": "",
    "overview": "Saddle Valentini Puffer is an interactive puffer sale where personality, beak care, and invert safety all matter. The catalog lists a minimum tank around 30+ gal. Adult size is listed around 4 in. Diet here is listed as Omnivore.",
    "overview_es": "",
    "facts": [
      "Adult size in this catalog is listed around 4 in.",
      "Plan around roughly 30+ gal or larger for long-term care.",
      "Diet in this catalog: Omnivore."
    ],
    "photoTitle": "Saddle Valentini Puffer",
    "inStock": false,
    "badges": [],
    "water": {
      "ph_low": 8,
      "ph_high": 8.4,
      "sal_low": 1.024,
      "sal_high": 1.026,
      "temp_low": 75,
      "temp_high": 80
    },
    "seasonal": null,
    "careLabel": "Intermediate",
    "visualCue": "Look for the rounded puffer body, beak-like mouth, and curious, interactive swimming style.",
    "bestWith": [
      "Mature systems that meet the minimum tank size",
      "Fish-only or mixed systems built around assertive livestock",
      "Semi-aggressive tankmates of similar size"
    ],
    "cautionWith": [
      "Tankmates that do not match its adult size or activity level",
      "Corals or polyps that could be nipped or disturbed"
    ],
    "staffNote": "",
    "headerSummary": "Interactive puffer profile with beak care and invertebrate compatibility trade-offs. Plan on roughly 30+ gal or larger long term.",
    "behavior": "Puffers are usually curious and interactive, inspecting rock, equipment, and anyone approaching the tank.",
    "feedingNotes": "Use a varied meaty diet and include harder items when appropriate so the beak and feeding behavior stay in good shape. Catalog diet listing: Omnivore.",
    "buyingGuidance": "Great personality sale, but only when the buyer accepts the trade-offs with invertebrates, nipping risk, and long-term feeding needs.",
    "recognitionNotes": "Look for the rounded puffer body, beak-like mouth, and curious, interactive swimming style."
  },
  {
    "id": "spiny-box-puffer",
    "name": "Spiny Box Puffer",
    "name_es": "Spiny Box Puffer",
    "aliases": [],
    "scientific": "Chilomycterus antillarum",
    "category": "Puffers",
    "type": "Saltwater Fish",
    "price": 0,
    "stockSize": "",
    "maxSize": "14 in",
    "minTank": "125+ gal",
    "diet": "Carnivore",
    "diet_es": "",
    "origin": "Unknown",
    "origin_es": "",
    "habitat": "Reef / rocky",
    "tankCode": "",
    "aggression": 38,
    "coralRisk": 78,
    "invertRisk": 20,
    "careDifficulty": 56,
    "role": "Interactive puffer profile with beak care and invertebrate compatibility trade-offs",
    "role_es": "",
    "overview": "Spiny Box Puffer is an interactive puffer sale where personality, beak care, and invert safety all matter. The catalog lists a minimum tank around 125+ gal. Adult size is listed around 14 in. Diet here is listed as Carnivore.",
    "overview_es": "",
    "facts": [
      "Adult size in this catalog is listed around 14 in.",
      "Plan around roughly 125+ gal or larger for long-term care.",
      "Diet in this catalog: Carnivore."
    ],
    "photoTitle": "Spiny Box Puffer",
    "inStock": false,
    "badges": [],
    "water": {
      "ph_low": 8,
      "ph_high": 8.4,
      "sal_low": 1.024,
      "sal_high": 1.026,
      "temp_low": 75,
      "temp_high": 80
    },
    "seasonal": null,
    "careLabel": "Intermediate",
    "visualCue": "Look for the rounded puffer body, beak-like mouth, and curious, interactive swimming style.",
    "bestWith": [
      "Mature systems that meet the minimum tank size",
      "Fish-only or mixed systems built around assertive livestock",
      "Semi-aggressive tankmates of similar size"
    ],
    "cautionWith": [
      "Tankmates that do not match its adult size or activity level",
      "Corals or polyps that could be nipped or disturbed"
    ],
    "staffNote": "",
    "headerSummary": "Interactive puffer profile with beak care and invertebrate compatibility trade-offs. Plan on roughly 125+ gal or larger long term.",
    "behavior": "Usually calmer than its look suggests, but still a big eater with a lot of tank presence.",
    "feedingNotes": "Use a robust meaty diet with shell-on foods to help control beak growth and wear.",
    "recognitionNotes": "Rounded body, short spines, and a burrfish-like face separate it from the sleeker puffers.",
    "buyingGuidance": "Best for a buyer who wants personality and accepts that this is an invertebrate-risk, heavy-waste fish."
  },
  {
    "id": "stars-and-stripes-puffer",
    "name": "Stars and Stripes Puffer",
    "name_es": "Stars and Stripes Puffer",
    "aliases": [],
    "scientific": "Arothron hispidus",
    "category": "Puffers",
    "type": "Saltwater Fish",
    "price": 0,
    "stockSize": "",
    "maxSize": "20 in",
    "minTank": "180+ gal",
    "diet": "Carnivore",
    "diet_es": "",
    "origin": "Unknown",
    "origin_es": "",
    "habitat": "Reef / rocky",
    "tankCode": "",
    "aggression": 38,
    "coralRisk": 78,
    "invertRisk": 20,
    "careDifficulty": 56,
    "role": "Interactive puffer profile with beak care and invertebrate compatibility trade-offs",
    "role_es": "",
    "overview": "Stars and Stripes Puffer is an interactive puffer sale where personality, beak care, and invert safety all matter. The catalog lists a minimum tank around 180+ gal. Adult size is listed around 20 in. Diet here is listed as Carnivore.",
    "overview_es": "",
    "facts": [
      "Adult size in this catalog is listed around 20 in.",
      "Plan around roughly 180+ gal or larger for long-term care.",
      "Diet in this catalog: Carnivore."
    ],
    "photoTitle": "Stars and Stripes Puffer",
    "inStock": false,
    "badges": [],
    "water": {
      "ph_low": 8,
      "ph_high": 8.4,
      "sal_low": 1.024,
      "sal_high": 1.026,
      "temp_low": 75,
      "temp_high": 80
    },
    "seasonal": null,
    "careLabel": "Intermediate",
    "visualCue": "Look for the rounded puffer body, beak-like mouth, and curious, interactive swimming style.",
    "bestWith": [
      "Mature systems that meet the minimum tank size",
      "Fish-only or mixed systems built around assertive livestock",
      "Semi-aggressive tankmates of similar size"
    ],
    "cautionWith": [
      "Tankmates that do not match its adult size or activity level",
      "Corals or polyps that could be nipped or disturbed"
    ],
    "staffNote": "",
    "headerSummary": "Interactive puffer profile with beak care and invertebrate compatibility trade-offs. Plan on roughly 180+ gal or larger long term.",
    "behavior": "Bold, food-motivated, and usually very aware of the room outside the tank.",
    "feedingNotes": "Offer a meaty varied diet with hard foods often enough to help keep the beak in shape.",
    "recognitionNotes": "Heavy body, blunt face, and the obvious striping/spotting pattern make it easy to spot.",
    "buyingGuidance": "Sell with adult size front and center. The fish is lovable, but the long-term bioload and invertebrate risk are substantial."
  },
  {
    "id": "yellow-boxfish",
    "name": "Yellow Boxfish",
    "name_es": "Yellow Boxfish",
    "aliases": [],
    "scientific": "Ostracion cubicus",
    "category": "Puffers",
    "type": "Saltwater Fish",
    "price": 0,
    "stockSize": "",
    "maxSize": "18 in",
    "minTank": "125+ gal",
    "diet": "Omnivore",
    "diet_es": "",
    "origin": "Unknown",
    "origin_es": "",
    "habitat": "Reef / rocky",
    "tankCode": "",
    "aggression": 38,
    "coralRisk": 78,
    "invertRisk": 20,
    "careDifficulty": 56,
    "role": "Interactive puffer profile with beak care and invertebrate compatibility trade-offs",
    "role_es": "",
    "overview": "Yellow Boxfish is an interactive puffer sale where personality, beak care, and invert safety all matter. The catalog lists a minimum tank around 125+ gal. Adult size is listed around 18 in. Diet here is listed as Omnivore.",
    "overview_es": "",
    "facts": [
      "Adult size in this catalog is listed around 18 in.",
      "Plan around roughly 125+ gal or larger for long-term care.",
      "Diet in this catalog: Omnivore."
    ],
    "photoTitle": "Yellow Boxfish",
    "inStock": false,
    "badges": [],
    "water": {
      "ph_low": 8,
      "ph_high": 8.4,
      "sal_low": 1.024,
      "sal_high": 1.026,
      "temp_low": 75,
      "temp_high": 80
    },
    "seasonal": null,
    "careLabel": "Intermediate",
    "visualCue": "Look for the rounded puffer body, beak-like mouth, and curious, interactive swimming style.",
    "bestWith": [
      "Mature systems that meet the minimum tank size",
      "Fish-only or mixed systems built around assertive livestock",
      "Semi-aggressive tankmates of similar size"
    ],
    "cautionWith": [
      "Tankmates that do not match its adult size or activity level",
      "Corals or polyps that could be nipped or disturbed"
    ],
    "staffNote": "",
    "headerSummary": "Interactive puffer profile with beak care and invertebrate compatibility trade-offs. Plan on roughly 125+ gal or larger long term.",
    "behavior": "Usually peaceful and oddly graceful, but easily stressed by chaotic or aggressive tankmates.",
    "feedingNotes": "Feed a broad omnivore routine and prioritize stability over fancy feeding tricks.",
    "recognitionNotes": "The box body and bright juvenile yellow pattern make this fish instantly recognizable.",
    "buyingGuidance": "This should be sold as a long-term oddball commitment, not a novelty fish for a casual mixed tank."
  }
];
