window.LTC_SPECIES_CHUNKS = window.LTC_SPECIES_CHUNKS || {};
window.LTC_SPECIES_CHUNKS["Clams"] = [
  {
    "id": "maxima-clam",
    "name": "Maxima Clam",
    "aliases": [
      "Giant Clam"
    ],
    "scientific": "Tridacna maxima",
    "category": "Clams",
    "type": "Invertebrate",
    "price": 0,
    "stockSize": "",
    "maxSize": "12 in",
    "minTank": "30+ gal",
    "careLabel": "Moderate",
    "diet": "Photosynthetic / filter feeder",
    "origin": "Indo-Pacific",
    "habitat": "Shallow reef flats with strong light",
    "tankCode": "",
    "aggression": 2,
    "coralRisk": 2,
    "invertRisk": 2,
    "careDifficulty": 36,
    "role": "Stunning living sculpture with iridescent mantle patterns",
    "visualCue": "Shell with an exposed fleshy mantle displaying vivid blues, greens, purples, and gold patterns that seem to glow under reef lighting.",
    "overview": "A living gem. The mantle patterns of a healthy maxima clam under reef lighting are among the most beautiful things in the entire aquarium hobby. Needs strong light and clean water.",
    "facts": [
      "The mantle patterns are unique to each individual — no two are identical.",
      "Needs strong lighting to thrive — PAR similar to SPS corals.",
      "Can close suddenly when startled — the snap is dramatic."
    ],
    "bestWith": [
      "Reef tanks with strong lighting",
      "Clean water with good calcium levels",
      "Prominent placement where the mantle is visible from above"
    ],
    "cautionWith": [
      "Low-light tanks",
      "Tanks with clam-nipping angelfish",
      "Poor water quality"
    ],
    "staffNote": "Show them from above with actinics on. The mantle under blue light sells itself.",
    "photoTitle": "Tridacna maxima",
    "inStock": false,
    "badges": [],
    "water": {
      "ph_low": 8.1,
      "ph_high": 8.4,
      "sal_low": 1.024,
      "sal_high": 1.026,
      "temp_low": 76,
      "temp_high": 82
    },
    "name_es": "Almeja Maxima",
    "overview_es": "Una gema viviente. Los patrones del manto bajo iluminación de arrecife son de las cosas más hermosas del hobby.",
    "role_es": "Escultura viviente impresionante con patrones iridiscentes",
    "diet_es": "Fotosintético / filtrador",
    "origin_es": "Indo-Pacífico",
    "headerSummary": "Stunning living sculpture with iridescent mantle patterns. Look for shell with an exposed fleshy mantle displaying vivid blues, greens, purples, and gold patterns that seem to glow under reef lighting. Plan on at least 30+ gal.",
    "seasonal": null
  },
  {
    "id": "crocea-clam",
    "name": "Crocea Clam",
    "name_es": "Crocea Clam",
    "aliases": [],
    "scientific": "Tridacna crocea",
    "category": "Clams",
    "type": "Invertebrate",
    "price": 0,
    "stockSize": "",
    "maxSize": "6 in",
    "minTank": "30+ gal",
    "diet": "Photosynthetic / filter feeder",
    "diet_es": "Fotosintético / filtrador",
    "origin": "Indo-Pacific",
    "origin_es": "Indo-Pacífico",
    "habitat": "Shallow reef rock and coral heads",
    "tankCode": "",
    "aggression": 14,
    "coralRisk": 28,
    "invertRisk": 20,
    "careDifficulty": 48,
    "role": "Smallest giant clam with intense mantle color and rock-boring habit",
    "role_es": "La almeja gigante más pequeña con color intenso y hábito de perforar roca",
    "overview": "The smallest of the giant clams, but not a beginner shortcut. Crocea clams want very strong light, a secure hard surface, and stable calcium and alkalinity if they are going to hold color and grow.",
    "overview_es": "La más pequeña de las almejas gigantes, pero no una opción fácil. Requiere luz muy fuerte, superficie dura segura y calcio/alcalinidad estables.",
    "facts": [
      "Often called the boring clam because it anchors into rock and can wear a pocket for itself.",
      "Usually demands stronger light than the larger sandbed giant clams.",
      "Small size makes placement easier, but chemistry still has to be rock solid."
    ],
    "photoTitle": "Crocea Clam",
    "inStock": false,
    "badges": [],
    "water": {
      "ph_low": 8.1,
      "ph_high": 8.4,
      "sal_low": 1.024,
      "sal_high": 1.026,
      "temp_low": 76,
      "temp_high": 82
    },
    "seasonal": null,
    "careLabel": "Moderate",
    "visualCue": "Compact clam with a vividly patterned mantle in blue, green, gold, or mixed colors, often seated tightly against rock.",
    "bestWith": [
      "Strongly lit mature reef tanks",
      "Flat rock or clam cradles for secure placement",
      "Buyers already maintaining calcium and alkalinity well"
    ],
    "cautionWith": [
      "Shaded mixed reefs",
      "Angels, butterflies, or other clam pickers",
      "Fresh tanks with unstable alkalinity or salinity"
    ],
    "staffNote": "Do not undersell it because it is the small clam. Smallest giant clam does not mean easiest giant clam.",
    "headerSummary": "Smallest giant clam with intense mantle color and rock-boring habit. Look for compact clam with a vividly patterned mantle in blue, green, gold, or mixed colors, often seated tightly against rock. Plan on at least 30+ gal."
  },
  {
    "id": "derasa-clam",
    "name": "Derasa Clam",
    "name_es": "Derasa Clam",
    "aliases": [],
    "scientific": "Tridacna derasa",
    "category": "Clams",
    "type": "Invertebrate",
    "price": 0,
    "stockSize": "",
    "maxSize": "20 in",
    "minTank": "75+ gal",
    "diet": "Photosynthetic / filter feeder",
    "diet_es": "Fotosintético / filtrador",
    "origin": "Indo-Pacific",
    "origin_es": "Indo-Pacífico",
    "habitat": "Lagoon sand and rubble bottoms",
    "tankCode": "",
    "aggression": 14,
    "coralRisk": 28,
    "invertRisk": 20,
    "careDifficulty": 40,
    "role": "Fast-growing giant clam that does well on the sandbed",
    "role_es": "Almeja gigante de rápido crecimiento que funciona bien sobre la arena",
    "overview": "One of the better giant clams for buyers moving into clam care because it is typically less light-hungry than crocea or maxima. The catch is size: a healthy Derasa can become a very large sandbed animal.",
    "overview_es": "Una de las mejores almejas gigantes para quien empieza con clams, aunque puede crecer muchísimo y dominar la zona de arena.",
    "facts": [
      "Often grows quickly when calcium, alkalinity, and lighting stay stable.",
      "Adults commonly settle on the sandbed instead of boring into rock.",
      "Small individuals may benefit from supplemental phytoplankton in very nutrient-poor systems."
    ],
    "photoTitle": "Derasa Clam",
    "inStock": false,
    "badges": [],
    "water": {
      "ph_low": 8.1,
      "ph_high": 8.4,
      "sal_low": 1.024,
      "sal_high": 1.026,
      "temp_low": 76,
      "temp_high": 82
    },
    "seasonal": null,
    "careLabel": "Moderate",
    "visualCue": "Broad mantle with striped gold, tan, or brown patterning over a smoother shell with fewer dramatic scutes.",
    "bestWith": [
      "Mature reef tanks with open sandbed room",
      "Moderate to strong lighting",
      "Buyers planning for long-term size rather than just current shell length"
    ],
    "cautionWith": [
      "Small tanks that cannot absorb a large adult clam",
      "Nipping angelfish or butterflyfish",
      "Weak calcium and alkalinity maintenance"
    ],
    "staffNote": "A very good clam sale when the buyer understands the eventual footprint. Sell the adult size, not the cute juvenile size.",
    "headerSummary": "Fast-growing giant clam that does well on the sandbed. Look for broad mantle with striped gold, tan, or brown patterning over a smoother shell with fewer dramatic scutes. Plan on at least 75+ gal."
  },
  {
    "id": "squamosa-clam",
    "name": "Squamosa Clam",
    "name_es": "Squamosa Clam",
    "aliases": [],
    "scientific": "Tridacna squamosa",
    "category": "Clams",
    "type": "Invertebrate",
    "price": 0,
    "stockSize": "",
    "maxSize": "16 in",
    "minTank": "75+ gal",
    "diet": "Photosynthetic / filter feeder",
    "diet_es": "Fotosintético / filtrador",
    "origin": "Indo-Pacific",
    "origin_es": "Indo-Pacífico",
    "habitat": "Lagoon bottoms and reef flats",
    "tankCode": "",
    "aggression": 14,
    "coralRisk": 28,
    "invertRisk": 20,
    "careDifficulty": 44,
    "role": "Large giant clam with dramatic fluted shell scutes",
    "role_es": "Gran almeja gigante con escamas y rebordes muy marcados en la concha",
    "overview": "A very showy giant clam that combines good color with a rugged, scaly shell shape. It usually does well on stable sand or flat rock placement, but it still needs strong light, chemistry stability, and room for a large adult.",
    "overview_es": "Una almeja gigante muy vistosa que combina buen color con una concha escamosa. Requiere luz fuerte, química estable y espacio para un adulto grande.",
    "facts": [
      "The pronounced shell scutes are the giveaway feature.",
      "Usually kept on the sandbed or another stable flat surface rather than wedged high on rock.",
      "Can become a major display animal and outgrow small or crowded reef systems."
    ],
    "photoTitle": "Squamosa Clam",
    "inStock": false,
    "badges": [],
    "water": {
      "ph_low": 8.1,
      "ph_high": 8.4,
      "sal_low": 1.024,
      "sal_high": 1.026,
      "temp_low": 76,
      "temp_high": 82
    },
    "seasonal": null,
    "careLabel": "Moderate",
    "visualCue": "Wide mantle over a heavy shell marked by prominent scutes or flared shell plates.",
    "bestWith": [
      "Open reef layouts with room for a big clam",
      "Stable calcium and alkalinity support",
      "Buyers wanting a dramatic shell form as much as mantle color"
    ],
    "cautionWith": [
      "Cramped nano or midsize reefs",
      "Fish that nip clam mantles",
      "Buying based only on juvenile size"
    ],
    "staffNote": "Strong premium clam sale, but confirm the buyer has the footprint and chemistry discipline for a long-term giant clam.",
    "headerSummary": "Large giant clam with dramatic fluted shell scutes. Look for wide mantle over a heavy shell marked by prominent scutes or flared shell plates. Plan on at least 75+ gal."
  },
  {
    "id": "flame-scallop",
    "name": "Flame Scallop",
    "name_es": "Vieira de Fuego",
    "scientific": "Ctenoides ales",
    "category": "Clams",
    "type": "Invertebrate",
    "aggression": 2,
    "coralRisk": 2,
    "invertRisk": 2,
    "careDifficulty": 88,
    "diet": "Filter feeder",
    "diet_es": "Filtrador",
    "origin": "Caribbean",
    "origin_es": "Caribe",
    "habitat": "Reef crevices",
    "maxSize": "3 in",
    "minTank": "30+ gal",
    "photoTitle": "Ctenoides_ales",
    "role": "Bright red filter feeder with flickering white reflective filaments",
    "role_es": "Filtrador rojo intenso con filamentos reflectantes blancos",
    "overview": "Spectacular looking, but usually a poor casual reef purchase. Flame scallops need frequent suspended microfoods, gentle secure placement, and low harassment; most slowly starve in ordinary mixed reefs.",
    "overview_es": "Espectacular visualmente, pero mala compra casual para la mayoría de arrecifes. Necesita microalimento suspendido frecuente, colocación segura y ausencia de acoso; la mayoría muere de hambre en arrecifes normales.",
    "inStock": false,
    "price": 0,
    "stockSize": "",
    "tankCode": "",
    "badges": [],
    "aliases": [],
    "facts": [
      "The flashing effect is reflective tissue action, not true bioluminescence.",
      "Most specimens fail in standard mixed reefs because they do not get enough suspended food over the long term.",
      "Best treated as specialist non-photosynthetic livestock, not as a routine decorative add-on."
    ],
    "water": {
      "ph_low": 8,
      "ph_high": 8.4,
      "sal_low": 1.023,
      "sal_high": 1.026,
      "temp_low": 75,
      "temp_high": 80
    },
    "seasonal": null,
    "careLabel": "Specialist",
    "visualCue": "Bright red shell opening lined with thin scarlet tentacles and shimmering white reflective filaments.",
    "bestWith": [
      "Dedicated high-feed or non-photosynthetic systems",
      "Shaded crevice placement with good suspended food delivery",
      "Buyers who already keep filter-feeding specialists successfully"
    ],
    "cautionWith": [
      "Ultra-clean reefs with little suspended nutrition",
      "Fish or crabs that pick at small bivalves",
      "Impulse decorative purchases"
    ],
    "staffNote": "This is an honesty sale. Gorgeous animal, but most buyers should be told no unless they already keep difficult filter feeders well.",
    "headerSummary": "Bright red filter feeder with flickering white reflective filaments. Look for bright red shell opening lined with thin scarlet tentacles and shimmering white reflective filaments. Plan on at least 30+ gal."
  }
];
