window.LTC_SPECIES_CHUNKS = window.LTC_SPECIES_CHUNKS || {};
window.LTC_SPECIES_CHUNKS["Starfish"] = [
  {
    "id": "sand-sifting-star",
    "name": "Sand Sifting Starfish",
    "aliases": [
      "White Sand Star"
    ],
    "scientific": "Astropecten polycanthus",
    "category": "Starfish",
    "type": "Invertebrate",
    "price": 0,
    "stockSize": "",
    "maxSize": "8 in",
    "minTank": "40+ gal",
    "careLabel": "Moderate",
    "diet": "Carnivore",
    "origin": "Indo-Pacific",
    "habitat": "Sandy reef flats",
    "tankCode": "",
    "aggression": 4,
    "coralRisk": 2,
    "invertRisk": 8,
    "careDifficulty": 34,
    "role": "Sand bed cleaner that processes and aerates substrate",
    "visualCue": "Flat five-armed star shape in tan to white color. Burrows through and under the sand.",
    "overview": "A sand bed utility animal that sifts through substrate eating detritus and small organisms. Effective at keeping sand clean but can strip a sand bed of beneficial fauna in smaller tanks.",
    "facts": [
      "Very effective at processing dirty sand beds.",
      "Can starve in small tanks after consuming all available food.",
      "Burrows under the sand — sometimes invisible for days."
    ],
    "bestWith": [
      "Large tanks with deep sand beds",
      "Tanks with dirty or neglected substrates",
      "Supplemental feeding plans"
    ],
    "cautionWith": [
      "Small tanks where it will strip the sand bed bare",
      "Tanks without supplemental feeding"
    ],
    "staffNote": "Works great in large tanks. In small tanks it'll eat everything and starve. Size-match the recommendation.",
    "photoTitle": "Astropecten polyacanthus",
    "inStock": false,
    "badges": [],
    "water": {
      "ph_low": 8.1,
      "ph_high": 8.4,
      "sal_low": 1.024,
      "sal_high": 1.026,
      "temp_low": 76,
      "temp_high": 80
    },
    "name_es": "Estrella Tamizadora de Arena",
    "overview_es": "Un animal utilitario que tamiza la arena comiendo detritus y organismos pequeños. Efectivo pero puede agotar la arena en acuarios pequeños.",
    "role_es": "Limpiador de arena que procesa y airea el sustrato",
    "diet_es": "Carnívoro",
    "origin_es": "Indo-Pacífico",
    "headerSummary": "Sand bed cleaner that processes and aerates substrate. Look for flat five-armed star shape in tan to white color. Burrows through and under the sand. Plan on at least 40+ gal.",
    "seasonal": null
  },
  {
    "id": "banded-serpent-star",
    "name": "Banded Serpent Star",
    "name_es": "Banded Serpent Star",
    "aliases": [],
    "scientific": "Ophioderma appressum",
    "category": "Starfish",
    "type": "Saltwater Invert",
    "price": 0,
    "stockSize": "",
    "maxSize": "10 in arm span",
    "minTank": "30+ gal",
    "diet": "Scavenger",
    "diet_es": "Carroñero / detritívoro",
    "origin": "Caribbean",
    "origin_es": "Caribe",
    "habitat": "Rock crevices and shaded cave areas",
    "tankCode": "",
    "aggression": 4,
    "coralRisk": 2,
    "invertRisk": 4,
    "careDifficulty": 18,
    "role": "Hardy serpent star that spends the day hidden and the evening scavenging for leftovers",
    "role_es": "Estrella quebradiza resistente para equipo de limpieza",
    "overview": "One of the better star-type sales for normal reef keepers because it is hardy, useful, and not nearly as fragile as linckias. It sells best when the buyer likes hidden scavengers and nighttime activity.",
    "overview_es": "Una estrella quebradiza resistente y segura para arrecife con atractivas bandas marrones y crema en los brazos.",
    "facts": [
      "Usually reaches out from a cave when food hits the tank.",
      "Much hardier than decorative reef stars like linckias.",
      "Needs rock crevices and moderate meaty leftovers or target feeding."
    ],
    "photoTitle": "Ophioderma appressum",
    "inStock": false,
    "badges": [],
    "water": {
      "ph_low": 8,
      "ph_high": 8.4,
      "sal_low": 1.024,
      "sal_high": 1.026,
      "temp_low": 75,
      "temp_high": 80
    },
    "seasonal": null,
    "careLabel": "Easy",
    "visualCue": "long thin flexible arms with banding and a small central disk hidden under rock.",
    "bestWith": [
      "Mixed reefs with caves",
      "Customers wanting a durable star-type invert",
      "Cleanup crews for leftover foods"
    ],
    "cautionWith": [
      "Tiny tanks with nowhere to hide",
      "Buyers expecting a bright daytime centerpiece",
      "Very aggressive predators"
    ],
    "staffNote": "Great practical star sale. Much safer than a delicate linckia for average hobbyists.",
    "headerSummary": "Hardy serpent star that spends the day hidden and the evening scavenging for leftovers. Look for long thin flexible arms with banding and a small central disk hidden under rock. Plan on at least 30+ gal."
  },
  {
    "id": "blue-linckia-starfish",
    "name": "Blue Linckia Starfish",
    "name_es": "Blue Linckia Starfish",
    "aliases": [],
    "scientific": "Linckia laevigata",
    "category": "Starfish",
    "type": "Saltwater Invert",
    "price": 0,
    "stockSize": "",
    "maxSize": "12 in",
    "minTank": "100+ gal",
    "diet": "Biofilm / microbial grazer",
    "diet_es": "",
    "origin": "Indo-Pacific",
    "origin_es": "",
    "habitat": "Mature reef rock and hard surfaces",
    "tankCode": "",
    "aggression": 0,
    "coralRisk": 2,
    "invertRisk": 0,
    "careDifficulty": 82,
    "role": "Delicate decorative sea star that should only be sold into large mature systems with real biofilm resources",
    "role_es": "",
    "overview": "These stars are beautiful, but they are shipping-sensitive and far less forgiving than casual buyers think. The right sale is an experienced reefer with a large mature tank, not someone filling out a cleanup crew list.",
    "overview_es": "",
    "facts": [
      "Often decline slowly in immature tanks even when parameters look fine on paper.",
      "Need mature rockwork and long-term stability more than they need a huge feeding event.",
      "Acclimation and handling matter because they are sensitive to sudden changes."
    ],
    "photoTitle": "Linckia laevigata",
    "inStock": false,
    "badges": [],
    "water": {
      "ph_low": 8,
      "ph_high": 8.4,
      "sal_low": 1.024,
      "sal_high": 1.026,
      "temp_low": 75,
      "temp_high": 80
    },
    "seasonal": null,
    "careLabel": "Expert",
    "visualCue": "bright blue body with smooth arms and a classic clean sea-star silhouette.",
    "bestWith": [
      "Large mature established reefs",
      "Experienced hobbyists",
      "Display-first tanks with strong long-term stability"
    ],
    "cautionWith": [
      "New tanks or recently reworked systems",
      "Impulse purchases based on color alone",
      "Customers treating it like a hardy cleanup animal"
    ],
    "staffNote": "Beautiful but high-risk. Make sure the buyer really has the kind of tank these need.",
    "headerSummary": "Delicate decorative sea star that should only be sold into large mature systems with real biofilm resources. Look for bright blue body with smooth arms and a classic clean sea-star silhouette. Plan on at least 100+ gal."
  },
  {
    "id": "brittle-star",
    "name": "Brittle Star",
    "name_es": "Brittle Star",
    "aliases": [],
    "scientific": "Ophiocoma sp.",
    "category": "Starfish",
    "type": "Saltwater Invert",
    "price": 0,
    "stockSize": "",
    "maxSize": "12 in arm span",
    "minTank": "30+ gal",
    "diet": "Scavenger",
    "diet_es": "",
    "origin": "Indo-Pacific / tropical Atlantic by species",
    "origin_es": "",
    "habitat": "Rock crevices and rubble",
    "tankCode": "",
    "aggression": 6,
    "coralRisk": 2,
    "invertRisk": 6,
    "careDifficulty": 18,
    "role": "Hardy scavenging star relative that hides in rockwork and helps pick through leftovers",
    "role_es": "",
    "overview": "A good practical oddball for customers who want movement after lights-out and something tougher than delicate decorative sea stars. These are about scavenging and character, not daytime color.",
    "overview_es": "",
    "facts": [
      "Usually remains tucked in rockwork during the day.",
      "Responds quickly to meaty foods and leftover feeding.",
      "Hardier than linckias and fromias for average keepers."
    ],
    "photoTitle": "Ophiocoma",
    "inStock": false,
    "badges": [],
    "water": {
      "ph_low": 8,
      "ph_high": 8.4,
      "sal_low": 1.024,
      "sal_high": 1.026,
      "temp_low": 75,
      "temp_high": 80
    },
    "seasonal": null,
    "careLabel": "Easy",
    "visualCue": "small central disk with long whiplike arms that snake through crevices at feeding time.",
    "bestWith": [
      "Rocky reef layouts",
      "Mixed reefs needing scavengers",
      "Customers comfortable with nocturnal behavior"
    ],
    "cautionWith": [
      "Expecting a bright visible show star all day",
      "Tiny systems with minimal rock cover",
      "Very aggressive fish that harass star arms"
    ],
    "staffNote": "An easy honest star-type recommendation when the buyer likes hidden cleanup behavior.",
    "headerSummary": "Hardy scavenging star relative that hides in rockwork and helps pick through leftovers. Look for small central disk with long whiplike arms that snake through crevices at feeding time. Plan on at least 30+ gal."
  },
  {
    "id": "chocolate-chip-starfish",
    "name": "Chocolate Chip Starfish",
    "name_es": "Chocolate Chip Starfish",
    "aliases": [],
    "scientific": "Protoreaster nodosus",
    "category": "Starfish",
    "type": "Saltwater Invert",
    "price": 0,
    "stockSize": "",
    "maxSize": "12 in",
    "minTank": "75+ gal",
    "diet": "Carnivore / omnivore",
    "diet_es": "",
    "origin": "Indo-Pacific",
    "origin_es": "",
    "habitat": "Sandy rubble areas and open bottoms",
    "tankCode": "",
    "aggression": 8,
    "coralRisk": 76,
    "invertRisk": 22,
    "careDifficulty": 22,
    "role": "Bold decorative sea star for fish-only and cautious non-reef systems, not for coral gardens",
    "role_es": "",
    "overview": "Very saleable because the look is iconic, but this one needs blunt honesty: it is not reef safe with decorative corals and sessile inverts. Great in the right fish-only display, bad surprise in the wrong reef.",
    "overview_es": "",
    "facts": [
      "Will eat or damage many corals, sponges, and other sessile inverts.",
      "Hardier than many decorative reef-safe stars.",
      "Best sold for fish-only or non-delicate displays."
    ],
    "photoTitle": "Protoreaster nodosus",
    "inStock": false,
    "badges": [],
    "water": {
      "ph_low": 8,
      "ph_high": 8.4,
      "sal_low": 1.024,
      "sal_high": 1.026,
      "temp_low": 75,
      "temp_high": 80
    },
    "seasonal": null,
    "careLabel": "Easy",
    "visualCue": "tan to cream star body with large dark cone-like nodules that look like chocolate chips.",
    "bestWith": [
      "Fish-only systems",
      "Large open-bottom displays",
      "Customers who want a bold daytime star"
    ],
    "cautionWith": [
      "Mixed coral reefs",
      "Delicate sessile inverts",
      "Buyers assuming every starfish is reef safe"
    ],
    "staffNote": "Strong visual seller, but the reef-safe conversation has to be direct.",
    "headerSummary": "Bold decorative sea star for fish-only and cautious non-reef systems, not for coral gardens. Look for tan to cream star body with large dark cone-like nodules that look like chocolate chips. Plan on at least 75+ gal."
  },
  {
    "id": "fromia-starfish",
    "name": "Fromia Starfish",
    "name_es": "Fromia Starfish",
    "aliases": [],
    "scientific": "Fromia milleporella",
    "category": "Starfish",
    "type": "Saltwater Invert",
    "price": 0,
    "stockSize": "",
    "maxSize": "5 in",
    "minTank": "60+ gal",
    "diet": "Biofilm / surface grazer",
    "diet_es": "",
    "origin": "Indo-Pacific",
    "origin_es": "",
    "habitat": "Mature reef rock surfaces",
    "tankCode": "",
    "aggression": 0,
    "coralRisk": 2,
    "invertRisk": 0,
    "careDifficulty": 68,
    "role": "More manageable than linckia stars but still a mature-tank decorative sea star, not a beginner cleanup item",
    "role_es": "",
    "overview": "Fromias are often a better decorative star choice than linckias, but they are still not casual starter animals. They belong with buyers who already keep mature stable reefs and understand starfish attrition risk.",
    "overview_es": "",
    "facts": [
      "Usually hardier than linckia species, but still sensitive compared with serpent and brittle stars.",
      "Need mature hard surfaces with natural films to browse.",
      "Do best in older stable systems with careful acclimation."
    ],
    "photoTitle": "Fromia milleporella",
    "inStock": false,
    "badges": [],
    "water": {
      "ph_low": 8,
      "ph_high": 8.4,
      "sal_low": 1.024,
      "sal_high": 1.026,
      "temp_low": 75,
      "temp_high": 80
    },
    "seasonal": null,
    "careLabel": "Expert",
    "visualCue": "small patterned reef star with a clean symmetrical look and slow deliberate movement over rock.",
    "bestWith": [
      "Established reef displays",
      "Experienced customers wanting a decorative star",
      "Systems with stable long-term parameters"
    ],
    "cautionWith": [
      "Immature tanks",
      "Impulse decorative purchases",
      "Expecting it to behave like a heavy scavenger"
    ],
    "staffNote": "Safer than a linckia does not mean easy. Make sure the buyer knows that.",
    "headerSummary": "More manageable than linckia stars but still a mature-tank decorative sea star, not a beginner cleanup item. Look for small patterned reef star with a clean symmetrical look and slow deliberate movement over rock. Plan on at least 60+ gal."
  },
  {
    "id": "green-brittle-star",
    "name": "Green Brittle Star",
    "name_es": "Green Brittle Star",
    "aliases": [],
    "scientific": "Ophiarachna incrassata",
    "category": "Starfish",
    "type": "Saltwater Invert",
    "price": 0,
    "stockSize": "",
    "maxSize": "18 in arm span",
    "minTank": "75+ gal",
    "diet": "Scavenger / opportunistic predator",
    "diet_es": "",
    "origin": "Indo-Pacific",
    "origin_es": "",
    "habitat": "Rock caves and overhangs",
    "tankCode": "",
    "aggression": 24,
    "coralRisk": 2,
    "invertRisk": 18,
    "careDifficulty": 32,
    "role": "Large dramatic brittle star better treated as a semi-predatory oddball than a harmless cleanup helper",
    "role_es": "",
    "overview": "A classic oddball, but not one to undersell. Bigger green brittles can become very opportunistic, so the proper buyer is someone who wants the animal itself and has tankmates sized accordingly.",
    "overview_es": "",
    "facts": [
      "Much bolder and more predatory than smaller serpent or brittle stars.",
      "Excellent scavenger, but capable of grabbing weak or tiny tankmates.",
      "Needs caves and room to spread its arms safely."
    ],
    "photoTitle": "Ophiarachna incrassata",
    "inStock": false,
    "badges": [],
    "water": {
      "ph_low": 8,
      "ph_high": 8.4,
      "sal_low": 1.024,
      "sal_high": 1.026,
      "temp_low": 75,
      "temp_high": 80
    },
    "seasonal": null,
    "careLabel": "Intermediate",
    "visualCue": "thick greenish arms with a larger central disk and a much heavier look than common serpent stars.",
    "bestWith": [
      "Larger fishy reef or FOWLR systems",
      "Oddball collectors",
      "Customers comfortable with opportunistic behavior"
    ],
    "cautionWith": [
      "Tiny gobies and delicate nano fish",
      "Crowded mixed invert displays",
      "Calling it harmless just because it is a star"
    ],
    "staffNote": "Very cool, but sell it like the opportunistic animal it is.",
    "headerSummary": "Large dramatic brittle star better treated as a semi-predatory oddball than a harmless cleanup helper. Look for thick greenish arms with a larger central disk and a much heavier look than common serpent stars. Plan on at least 75+ gal."
  },
  {
    "id": "orange-linckia-starfish",
    "name": "Orange Linckia Starfish",
    "name_es": "Orange Linckia Starfish",
    "aliases": [],
    "scientific": "Linckia multifora",
    "category": "Starfish",
    "type": "Saltwater Invert",
    "price": 0,
    "stockSize": "",
    "maxSize": "12 in",
    "minTank": "100+ gal",
    "diet": "Biofilm / microbial grazer",
    "diet_es": "",
    "origin": "Indo-Pacific",
    "origin_es": "",
    "habitat": "Mature reef rock and hard surfaces",
    "tankCode": "",
    "aggression": 0,
    "coralRisk": 2,
    "invertRisk": 0,
    "careDifficulty": 82,
    "role": "Delicate decorative sea star that should only be sold into large mature systems with real biofilm resources",
    "role_es": "",
    "overview": "These stars are beautiful, but they are shipping-sensitive and far less forgiving than casual buyers think. The right sale is an experienced reefer with a large mature tank, not someone filling out a cleanup crew list.",
    "overview_es": "",
    "facts": [
      "Often decline slowly in immature tanks even when parameters look fine on paper.",
      "Need mature rockwork and long-term stability more than they need a huge feeding event.",
      "Acclimation and handling matter because they are sensitive to sudden changes."
    ],
    "photoTitle": "Linckia multifora",
    "inStock": false,
    "badges": [],
    "water": {
      "ph_low": 8,
      "ph_high": 8.4,
      "sal_low": 1.024,
      "sal_high": 1.026,
      "temp_low": 75,
      "temp_high": 80
    },
    "seasonal": null,
    "careLabel": "Expert",
    "visualCue": "orange to orange-red body with smooth arms and a classic clean sea-star silhouette.",
    "bestWith": [
      "Large mature established reefs",
      "Experienced hobbyists",
      "Display-first tanks with strong long-term stability"
    ],
    "cautionWith": [
      "New tanks or recently reworked systems",
      "Impulse purchases based on color alone",
      "Customers treating it like a hardy cleanup animal"
    ],
    "staffNote": "Beautiful but high-risk. Make sure the buyer really has the kind of tank these need.",
    "headerSummary": "Delicate decorative sea star that should only be sold into large mature systems with real biofilm resources. Look for orange to orange-red body with smooth arms and a classic clean sea-star silhouette. Plan on at least 100+ gal."
  },
  {
    "id": "red-fromia-starfish",
    "name": "Red Fromia Starfish",
    "name_es": "Red Fromia Starfish",
    "aliases": [],
    "scientific": "Fromia milleporella",
    "category": "Starfish",
    "type": "Saltwater Invert",
    "price": 0,
    "stockSize": "",
    "maxSize": "5 in",
    "minTank": "60+ gal",
    "diet": "Biofilm / surface grazer",
    "diet_es": "",
    "origin": "Indo-Pacific",
    "origin_es": "",
    "habitat": "Mature reef rock surfaces",
    "tankCode": "",
    "aggression": 0,
    "coralRisk": 2,
    "invertRisk": 0,
    "careDifficulty": 68,
    "role": "More manageable than linckia stars but still a mature-tank decorative sea star, not a beginner cleanup item",
    "role_es": "",
    "overview": "Fromias are often a better decorative star choice than linckias, but they are still not casual starter animals. They belong with buyers who already keep mature stable reefs and understand starfish attrition risk.",
    "overview_es": "",
    "facts": [
      "Usually hardier than linckia species, but still sensitive compared with serpent and brittle stars.",
      "Need mature hard surfaces with natural films to browse.",
      "Do best in older stable systems with careful acclimation."
    ],
    "photoTitle": "Fromia milleporella",
    "inStock": false,
    "badges": [],
    "water": {
      "ph_low": 8,
      "ph_high": 8.4,
      "sal_low": 1.024,
      "sal_high": 1.026,
      "temp_low": 75,
      "temp_high": 80
    },
    "seasonal": null,
    "careLabel": "Expert",
    "visualCue": "small patterned reef star with a clean symmetrical look and slow deliberate movement over rock.",
    "bestWith": [
      "Established reef displays",
      "Experienced customers wanting a decorative star",
      "Systems with stable long-term parameters"
    ],
    "cautionWith": [
      "Immature tanks",
      "Impulse decorative purchases",
      "Expecting it to behave like a heavy scavenger"
    ],
    "staffNote": "Safer than a linckia does not mean easy. Make sure the buyer knows that.",
    "headerSummary": "More manageable than linckia stars but still a mature-tank decorative sea star, not a beginner cleanup item. Look for small patterned reef star with a clean symmetrical look and slow deliberate movement over rock. Plan on at least 60+ gal."
  },
  {
    "id": "red-linckia-starfish",
    "name": "Red Linckia Starfish",
    "name_es": "Red Linckia Starfish",
    "aliases": [],
    "scientific": "Linckia sp.",
    "category": "Starfish",
    "type": "Saltwater Invert",
    "price": 0,
    "stockSize": "",
    "maxSize": "12 in",
    "minTank": "100+ gal",
    "diet": "Biofilm / microbial grazer",
    "diet_es": "",
    "origin": "Indo-Pacific",
    "origin_es": "",
    "habitat": "Mature reef rock and hard surfaces",
    "tankCode": "",
    "aggression": 0,
    "coralRisk": 2,
    "invertRisk": 0,
    "careDifficulty": 82,
    "role": "Delicate decorative sea star that should only be sold into large mature systems with real biofilm resources",
    "role_es": "",
    "overview": "These stars are beautiful, but they are shipping-sensitive and far less forgiving than casual buyers think. The right sale is an experienced reefer with a large mature tank, not someone filling out a cleanup crew list.",
    "overview_es": "",
    "facts": [
      "Often decline slowly in immature tanks even when parameters look fine on paper.",
      "Need mature rockwork and long-term stability more than they need a huge feeding event.",
      "Acclimation and handling matter because they are sensitive to sudden changes."
    ],
    "photoTitle": "Linckia sp.",
    "inStock": false,
    "badges": [],
    "water": {
      "ph_low": 8,
      "ph_high": 8.4,
      "sal_low": 1.024,
      "sal_high": 1.026,
      "temp_low": 75,
      "temp_high": 80
    },
    "seasonal": null,
    "careLabel": "Expert",
    "visualCue": "red body with smooth arms and a classic clean sea-star silhouette.",
    "bestWith": [
      "Large mature established reefs",
      "Experienced hobbyists",
      "Display-first tanks with strong long-term stability"
    ],
    "cautionWith": [
      "New tanks or recently reworked systems",
      "Impulse purchases based on color alone",
      "Customers treating it like a hardy cleanup animal"
    ],
    "staffNote": "Beautiful but high-risk. Make sure the buyer really has the kind of tank these need.",
    "headerSummary": "Delicate decorative sea star that should only be sold into large mature systems with real biofilm resources. Look for red body with smooth arms and a classic clean sea-star silhouette. Plan on at least 100+ gal."
  },
  {
    "id": "serpent-star",
    "name": "Serpent Star",
    "name_es": "Serpent Star",
    "aliases": [],
    "scientific": "Ophioderma sp.",
    "category": "Starfish",
    "type": "Saltwater Invert",
    "price": 0,
    "stockSize": "",
    "maxSize": "12 in arm span",
    "minTank": "30+ gal",
    "diet": "Scavenger",
    "diet_es": "",
    "origin": "Tropical marine reefs",
    "origin_es": "",
    "habitat": "Caves and rock crevices",
    "tankCode": "",
    "aggression": 4,
    "coralRisk": 2,
    "invertRisk": 4,
    "careDifficulty": 18,
    "role": "Hardy nocturnal scavenger that is usually one of the safest star-type recommendations in the hobby",
    "role_es": "",
    "overview": "A great bridge between weird and practical. Serpent stars are useful, hardy, and far easier to place successfully than decorative reef stars, which makes them an excellent honest recommendation.",
    "overview_es": "",
    "facts": [
      "Usually hides during the day and scavenges actively at feeding time.",
      "Hardier than linckia and fromia stars.",
      "Needs some rock structure to settle comfortably."
    ],
    "photoTitle": "Ophioderma",
    "inStock": false,
    "badges": [],
    "water": {
      "ph_low": 8,
      "ph_high": 8.4,
      "sal_low": 1.024,
      "sal_high": 1.026,
      "temp_low": 75,
      "temp_high": 80
    },
    "seasonal": null,
    "careLabel": "Easy",
    "visualCue": "slender flexible arms extending from rockwork whenever food hits the water.",
    "bestWith": [
      "Mixed reefs with caves",
      "Cleanup crews that need a nocturnal scavenger",
      "Customers wanting star behavior without expert care"
    ],
    "cautionWith": [
      "Expecting a bright visible daytime centerpiece",
      "Tiny bare systems with little cover",
      "Very aggressive predators"
    ],
    "staffNote": "Easy star-type recommendation when the buyer likes scavengers and caves.",
    "headerSummary": "Hardy nocturnal scavenger that is usually one of the safest star-type recommendations in the hobby. Look for slender flexible arms extending from rockwork whenever food hits the water. Plan on at least 30+ gal."
  },
  {
    "id": "pods-starter-culture",
    "name": "Pods Starter Culture",
    "name_es": "Pods Starter Culture",
    "aliases": [],
    "scientific": "Mixed copepods / amphipods culture",
    "category": "Starfish",
    "type": "Saltwater Invert",
    "price": 0,
    "stockSize": "",
    "maxSize": "Microscopic to a few millimeters",
    "minTank": "Any stable refugium or display with pod support",
    "diet": "Detritus / film / microalgae",
    "diet_es": "",
    "origin": "Aquacultured live-food blend",
    "origin_es": "",
    "habitat": "Refugia, chaeto, rock pores, and sand beds",
    "tankCode": "",
    "aggression": 0,
    "coralRisk": 0,
    "invertRisk": 0,
    "careDifficulty": 12,
    "role": "Live microfauna culture used to seed biodiversity and support pod-eating fish",
    "role_es": "",
    "overview": "Live microfauna culture used to seed biodiversity, strengthen refugia, and support pod-eating fish.",
    "overview_es": "",
    "facts": [
      "Works best when the system has rock, macroalgae, or refugium space to protect the population.",
      "Predators can reduce visible pod numbers quickly in open displays.",
      "Useful as a starter culture or periodic booster, not a decorative livestock piece."
    ],
    "photoTitle": "Copepod",
    "inStock": false,
    "badges": [],
    "water": {
      "ph_low": 8,
      "ph_high": 8.4,
      "sal_low": 1.024,
      "sal_high": 1.026,
      "temp_low": 75,
      "temp_high": 80
    },
    "seasonal": null,
    "careLabel": "Easy",
    "visualCue": "tiny fast-moving specks scattered through algae, rock pores, and glass at night.",
    "bestWith": [
      "Mandarin-support systems",
      "Refugia",
      "Customers building biodiversity"
    ],
    "cautionWith": [
      "Expecting a visible permanent swarm in a predator display",
      "Sterile brand-new systems with no safe habitat",
      "Selling it as if it were a cleanup crab or snail"
    ],
    "staffNote": "Good support product. Sell the function clearly.",
    "headerSummary": "Live microfauna culture used to seed biodiversity and support pod-eating fish. Look for tiny fast-moving specks scattered through algae, rock pores, and glass at night. Plan on at least Any stable refugium or display with pod support."
  }
];
