window.LTC_SPECIES_CHUNKS = window.LTC_SPECIES_CHUNKS || {};
window.LTC_SPECIES_CHUNKS["Rabbitfish"] = [
  {
    "id": "foxface",
    "name": "Foxface Rabbitfish",
    "aliases": [
      "Foxface Lo"
    ],
    "scientific": "Siganus vulpinus",
    "category": "Rabbitfish",
    "type": "Saltwater Fish",
    "price": 0,
    "stockSize": "",
    "maxSize": "9 in",
    "minTank": "125+ gal",
    "careLabel": "Easy",
    "diet": "Herbivore",
    "origin": "Western Pacific",
    "habitat": "Lagoons and outer reef slopes",
    "tankCode": "",
    "aggression": 20,
    "coralRisk": 12,
    "invertRisk": 4,
    "careDifficulty": 24,
    "role": "Peaceful algae destroyer with venomous spines",
    "visualCue": "Bright yellow body with bold black and white face markings and an elongated snout.",
    "overview": "A fantastic algae eater that's peaceful, hardy, and effective. The venomous dorsal spines demand respect during handling but are no issue in the tank.",
    "facts": [
      "Arguably the best algae-eating fish available for larger tanks.",
      "Venomous spines — handle with care during netting and acclimation.",
      "Changes color to mottled brown when stressed or sleeping — this is normal."
    ],
    "bestWith": [
      "Larger reef tanks with algae",
      "Peaceful to semi-aggressive communities",
      "Owners wanting natural algae control"
    ],
    "cautionWith": [
      "Bare hands during handling",
      "Very small tanks",
      "Occasionally may nip at soft corals if underfed"
    ],
    "staffNote": "Always warn about the spines. Great fish but customers need to know about safe handling.",
    "photoTitle": "Siganus vulpinus",
    "inStock": false,
    "badges": [],
    "water": {
      "ph_low": 8,
      "ph_high": 8.4,
      "sal_low": 1.024,
      "sal_high": 1.026,
      "temp_low": 75,
      "temp_high": 80
    },
    "name_es": "Pez Conejo Cara de Zorro",
    "overview_es": "Un pez herbívoro vibrante amarillo con marcas blancas y negras en la cara. Tiene espinas dorsales venenosas.",
    "role_es": "Herbívoro amarillo con espinas venenosas",
    "diet_es": "Herbívoro",
    "origin_es": "Pacífico Occidental",
    "headerSummary": "Steady algae grazer with calm presence and real utility in larger reef systems. Look for bright yellow body with bold black and white face markings and an elongated snout. Plan on at least 125+ gal.",
    "seasonal": null,
    "behavior": "Steady algae grazer with a calm overall presence and long grazing passes across rock and glass. Rabbitfish are usually easier community additions than they look, but they still need room and deserve respect because of their venomous dorsal spines.",
    "feedingNotes": "Make algae support part of the routine, not an afterthought. Seaweed sheets, herbivore pellets, and occasional frozen rotation usually keep rabbitfish in better long-term condition.",
    "buyingGuidance": "A strong recommendation when the buyer wants algae help and a larger peaceful display fish, but the conversation should still include spine caution and the need for long-term room.",
    "recognitionNotes": "Bright yellow body with bold black and white face markings and an elongated snout."
  },
  {
    "id": "blue-spotted-rabbitfish",
    "name": "Blue Spotted Rabbitfish",
    "name_es": "Blue Spotted Rabbitfish",
    "aliases": [],
    "scientific": "Siganus corallinus",
    "category": "Rabbitfish",
    "type": "Saltwater Fish",
    "price": 0,
    "stockSize": "",
    "maxSize": "8 in",
    "minTank": "120+ gal",
    "diet": "Herbivore",
    "diet_es": "",
    "origin": "Unknown",
    "origin_es": "",
    "habitat": "Reef / rocky",
    "tankCode": "",
    "aggression": 38,
    "coralRisk": 28,
    "invertRisk": 20,
    "careDifficulty": 42,
    "role": "Roomy algae grazer with calm behavior and venomous dorsal spines",
    "role_es": "",
    "overview": "Blue Spotted Rabbitfish is a roomy algae grazer with useful browsing behavior and venomous dorsal spines.",
    "overview_es": "",
    "facts": [
      "Plan around a roomy, species-appropriate tank for long-term care.",
      "Temperament is usually workable in a well-planned community with sensible tankmates.",
      "Venomous dorsal spines and long-term swimming room both deserve mention before the sale."
    ],
    "photoTitle": "Blue Spotted Rabbitfish",
    "inStock": false,
    "badges": [],
    "water": {
      "ph_low": 8,
      "ph_high": 8.4,
      "sal_low": 1.024,
      "sal_high": 1.026,
      "temp_low": 75,
      "temp_high": 80
    },
    "seasonal": null,
    "careLabel": "Intermediate",
    "visualCue": "Look for the foxface/rabbitfish body shape, browsing behavior, and dorsal spines.",
    "bestWith": [
      "Mature systems that meet the minimum tank size",
      "Tankmates chosen around its behavior and adult size",
      "Semi-aggressive tankmates of similar size"
    ],
    "cautionWith": [
      "Tankmates that do not match its adult size or activity level",
      "Corals or polyps that could be nipped or disturbed"
    ],
    "staffNote": "",
    "headerSummary": "Roomy algae grazer with calm behavior and venomous dorsal spines. Room and spine safety both matter as much as algae utility.",
    "behavior": "Steady algae grazer with a calm overall presence and long grazing passes across rock and glass. Rabbitfish are usually easier community additions than they look, but they still need room and deserve respect because of their venomous dorsal spines.",
    "feedingNotes": "Make algae support part of the routine, not an afterthought. Seaweed sheets, herbivore pellets, and occasional frozen rotation usually keep rabbitfish in better long-term condition.",
    "buyingGuidance": "A strong recommendation when the buyer wants algae help and a larger peaceful display fish, but the conversation should still include spine caution and the need for long-term room.",
    "recognitionNotes": "Look for the foxface/rabbitfish body shape, browsing behavior, and dorsal spines."
  },
  {
    "id": "foxface-lo",
    "name": "Foxface Lo",
    "name_es": "Foxface Lo",
    "aliases": [],
    "scientific": "Siganus vulpinus",
    "category": "Rabbitfish",
    "type": "Saltwater Fish",
    "price": 0,
    "stockSize": "",
    "maxSize": "9 in",
    "minTank": "125+ gal",
    "diet": "Herbivore",
    "diet_es": "",
    "origin": "Unknown",
    "origin_es": "",
    "habitat": "Reef / rocky",
    "tankCode": "",
    "aggression": 38,
    "coralRisk": 28,
    "invertRisk": 20,
    "careDifficulty": 42,
    "role": "Roomy algae grazer with calm behavior and venomous dorsal spines",
    "role_es": "",
    "overview": "Foxface Lo is a roomy algae grazer with useful browsing behavior and venomous dorsal spines.",
    "overview_es": "",
    "facts": [
      "Plan around a roomy, species-appropriate tank for long-term care.",
      "Temperament is usually workable in a well-planned community with sensible tankmates.",
      "Venomous dorsal spines and long-term swimming room both deserve mention before the sale."
    ],
    "photoTitle": "Foxface Lo",
    "inStock": false,
    "badges": [],
    "water": {
      "ph_low": 8,
      "ph_high": 8.4,
      "sal_low": 1.024,
      "sal_high": 1.026,
      "temp_low": 75,
      "temp_high": 80
    },
    "seasonal": null,
    "careLabel": "Intermediate",
    "visualCue": "Look for the foxface/rabbitfish body shape, browsing behavior, and dorsal spines.",
    "bestWith": [
      "Mature systems that meet the minimum tank size",
      "Tankmates chosen around its behavior and adult size",
      "Semi-aggressive tankmates of similar size"
    ],
    "cautionWith": [
      "Tankmates that do not match its adult size or activity level",
      "Corals or polyps that could be nipped or disturbed"
    ],
    "staffNote": "",
    "headerSummary": "Roomy algae grazer with calm behavior and venomous dorsal spines. Room and spine safety both matter as much as algae utility.",
    "behavior": "Steady algae grazer with a calm overall presence and long grazing passes across rock and glass. Rabbitfish are usually easier community additions than they look, but they still need room and deserve respect because of their venomous dorsal spines.",
    "feedingNotes": "Make algae support part of the routine, not an afterthought. Seaweed sheets, herbivore pellets, and occasional frozen rotation usually keep rabbitfish in better long-term condition.",
    "buyingGuidance": "A strong recommendation when the buyer wants algae help and a larger peaceful display fish, but the conversation should still include spine caution and the need for long-term room.",
    "recognitionNotes": "Look for the foxface/rabbitfish body shape, browsing behavior, and dorsal spines."
  },
  {
    "id": "magnificent-foxface",
    "name": "Magnificent Foxface",
    "name_es": "Magnificent Foxface",
    "aliases": [],
    "scientific": "Siganus magnificus",
    "category": "Rabbitfish",
    "type": "Saltwater Fish",
    "price": 0,
    "stockSize": "",
    "maxSize": "9 in",
    "minTank": "100+ gal",
    "diet": "Herbivore",
    "diet_es": "Herbívoro",
    "origin": "Eastern Indian Ocean",
    "origin_es": "Océano Índico Oriental",
    "habitat": "Coral reefs",
    "tankCode": "",
    "aggression": 25,
    "coralRisk": 10,
    "invertRisk": 5,
    "careDifficulty": 30,
    "role": "Elegant black and white foxface rabbitfish",
    "role_es": "Pez conejo cara de zorro elegante blanco y negro",
    "overview": "A more elegantly patterned cousin of the common Foxface with a dramatic black and white face pattern. Same venomous spine warning applies. Excellent algae eater.",
    "overview_es": "Un primo con patrón más elegante del Cara de Zorro común con un dramático patrón facial blanco y negro.",
    "facts": [
      "Adult size in this catalog is listed around 9 in.",
      "Plan around roughly 100+ gal or larger for long-term care.",
      "Diet in this catalog: Herbivore."
    ],
    "photoTitle": "Siganus_magnificus",
    "inStock": false,
    "badges": [],
    "water": {
      "ph_low": 8,
      "ph_high": 8.4,
      "sal_low": 1.024,
      "sal_high": 1.026,
      "temp_low": 75,
      "temp_high": 80
    },
    "seasonal": null,
    "careLabel": "Moderate",
    "visualCue": "Look for the foxface/rabbitfish body shape, browsing behavior, and dorsal spines.",
    "bestWith": [
      "Mature systems that meet the minimum tank size",
      "Reef-safe community plans with compatible tankmates",
      "Peaceful to semi-peaceful community livestock"
    ],
    "cautionWith": [
      "Tankmates that do not match its adult size or activity level",
      "Systems smaller than 100+ gal"
    ],
    "staffNote": "",
    "headerSummary": "Elegant black and white foxface rabbitfish. Plan on roughly 100+ gal or larger long term.",
    "behavior": "Steady algae grazer with a calm overall presence and long grazing passes across rock and glass. Rabbitfish are usually easier community additions than they look, but they still need room and deserve respect because of their venomous dorsal spines.",
    "feedingNotes": "Make algae support part of the routine, not an afterthought. Seaweed sheets, herbivore pellets, and occasional frozen rotation usually keep rabbitfish in better long-term condition.",
    "buyingGuidance": "A strong recommendation when the buyer wants algae help and a larger peaceful display fish, but the conversation should still include spine caution and the need for long-term room.",
    "recognitionNotes": "Look for the foxface/rabbitfish body shape, browsing behavior, and dorsal spines."
  },
  {
    "id": "masked-rabbitfish",
    "name": "Masked Rabbitfish",
    "name_es": "Masked Rabbitfish",
    "aliases": [],
    "scientific": "Siganus puellus",
    "category": "Rabbitfish",
    "type": "Saltwater Fish",
    "price": 0,
    "stockSize": "",
    "maxSize": "10 in",
    "minTank": "125+ gal",
    "diet": "Herbivore",
    "diet_es": "",
    "origin": "Unknown",
    "origin_es": "",
    "habitat": "Reef / rocky",
    "tankCode": "",
    "aggression": 38,
    "coralRisk": 28,
    "invertRisk": 20,
    "careDifficulty": 42,
    "role": "Roomy algae grazer with calm behavior and venomous dorsal spines",
    "role_es": "",
    "overview": "Masked Rabbitfish is a roomy algae grazer with useful browsing behavior and venomous dorsal spines.",
    "overview_es": "",
    "facts": [
      "Plan around a roomy, species-appropriate tank for long-term care.",
      "Temperament is usually workable in a well-planned community with sensible tankmates.",
      "Venomous dorsal spines and long-term swimming room both deserve mention before the sale."
    ],
    "photoTitle": "Masked Rabbitfish",
    "inStock": false,
    "badges": [],
    "water": {
      "ph_low": 8,
      "ph_high": 8.4,
      "sal_low": 1.024,
      "sal_high": 1.026,
      "temp_low": 75,
      "temp_high": 80
    },
    "seasonal": null,
    "careLabel": "Intermediate",
    "visualCue": "Look for the foxface/rabbitfish body shape, browsing behavior, and dorsal spines.",
    "bestWith": [
      "Mature systems that meet the minimum tank size",
      "Tankmates chosen around its behavior and adult size",
      "Semi-aggressive tankmates of similar size"
    ],
    "cautionWith": [
      "Tankmates that do not match its adult size or activity level",
      "Corals or polyps that could be nipped or disturbed"
    ],
    "staffNote": "",
    "headerSummary": "Roomy algae grazer with calm behavior and venomous dorsal spines. Room and spine safety both matter as much as algae utility.",
    "behavior": "Steady algae grazer with a calm overall presence and long grazing passes across rock and glass. Rabbitfish are usually easier community additions than they look, but they still need room and deserve respect because of their venomous dorsal spines.",
    "feedingNotes": "Make algae support part of the routine, not an afterthought. Seaweed sheets, herbivore pellets, and occasional frozen rotation usually keep rabbitfish in better long-term condition.",
    "buyingGuidance": "A strong recommendation when the buyer wants algae help and a larger peaceful display fish, but the conversation should still include spine caution and the need for long-term room.",
    "recognitionNotes": "Look for the foxface/rabbitfish body shape, browsing behavior, and dorsal spines."
  },
  {
    "id": "one-spot-foxface",
    "name": "One Spot Foxface",
    "name_es": "One Spot Foxface",
    "aliases": [],
    "scientific": "Siganus unimaculatus",
    "category": "Rabbitfish",
    "type": "Saltwater Fish",
    "price": 0,
    "stockSize": "",
    "maxSize": "8 in",
    "minTank": "100+ gal",
    "diet": "Herbivore",
    "diet_es": "",
    "origin": "Unknown",
    "origin_es": "",
    "habitat": "Reef / rocky",
    "tankCode": "",
    "aggression": 38,
    "coralRisk": 28,
    "invertRisk": 20,
    "careDifficulty": 42,
    "role": "Roomy algae grazer with calm behavior and venomous dorsal spines",
    "role_es": "",
    "overview": "One Spot Foxface is a roomy algae grazer with useful browsing behavior and venomous dorsal spines.",
    "overview_es": "",
    "facts": [
      "Plan around a roomy, species-appropriate tank for long-term care.",
      "Temperament is usually workable in a well-planned community with sensible tankmates.",
      "Venomous dorsal spines and long-term swimming room both deserve mention before the sale."
    ],
    "photoTitle": "One Spot Foxface",
    "inStock": false,
    "badges": [],
    "water": {
      "ph_low": 8,
      "ph_high": 8.4,
      "sal_low": 1.024,
      "sal_high": 1.026,
      "temp_low": 75,
      "temp_high": 80
    },
    "seasonal": null,
    "careLabel": "Intermediate",
    "visualCue": "Look for the foxface/rabbitfish body shape, browsing behavior, and dorsal spines.",
    "bestWith": [
      "Mature systems that meet the minimum tank size",
      "Tankmates chosen around its behavior and adult size",
      "Semi-aggressive tankmates of similar size"
    ],
    "cautionWith": [
      "Tankmates that do not match its adult size or activity level",
      "Corals or polyps that could be nipped or disturbed"
    ],
    "staffNote": "",
    "headerSummary": "Roomy algae grazer with calm behavior and venomous dorsal spines. Room and spine safety both matter as much as algae utility.",
    "behavior": "Steady algae grazer with a calm overall presence and long grazing passes across rock and glass. Rabbitfish are usually easier community additions than they look, but they still need room and deserve respect because of their venomous dorsal spines.",
    "feedingNotes": "Make algae support part of the routine, not an afterthought. Seaweed sheets, herbivore pellets, and occasional frozen rotation usually keep rabbitfish in better long-term condition.",
    "buyingGuidance": "A strong recommendation when the buyer wants algae help and a larger peaceful display fish, but the conversation should still include spine caution and the need for long-term room.",
    "recognitionNotes": "Look for the foxface/rabbitfish body shape, browsing behavior, and dorsal spines."
  },
  {
    "id": "scribbled-rabbitfish",
    "name": "Scribbled Rabbitfish",
    "name_es": "Scribbled Rabbitfish",
    "aliases": [],
    "scientific": "Siganus spinus",
    "category": "Rabbitfish",
    "type": "Saltwater Fish",
    "price": 0,
    "stockSize": "",
    "maxSize": "10 in",
    "minTank": "125+ gal",
    "diet": "Herbivore",
    "diet_es": "",
    "origin": "Unknown",
    "origin_es": "",
    "habitat": "Reef / rocky",
    "tankCode": "",
    "aggression": 38,
    "coralRisk": 28,
    "invertRisk": 20,
    "careDifficulty": 42,
    "role": "Roomy algae grazer with calm behavior and venomous dorsal spines",
    "role_es": "",
    "overview": "Scribbled Rabbitfish is a roomy algae grazer with useful browsing behavior and venomous dorsal spines.",
    "overview_es": "",
    "facts": [
      "Plan around a roomy, species-appropriate tank for long-term care.",
      "Temperament is usually workable in a well-planned community with sensible tankmates.",
      "Venomous dorsal spines and long-term swimming room both deserve mention before the sale."
    ],
    "photoTitle": "Scribbled Rabbitfish",
    "inStock": false,
    "badges": [],
    "water": {
      "ph_low": 8,
      "ph_high": 8.4,
      "sal_low": 1.024,
      "sal_high": 1.026,
      "temp_low": 75,
      "temp_high": 80
    },
    "seasonal": null,
    "careLabel": "Intermediate",
    "visualCue": "Look for the foxface/rabbitfish body shape, browsing behavior, and dorsal spines.",
    "bestWith": [
      "Mature systems that meet the minimum tank size",
      "Tankmates chosen around its behavior and adult size",
      "Semi-aggressive tankmates of similar size"
    ],
    "cautionWith": [
      "Tankmates that do not match its adult size or activity level",
      "Corals or polyps that could be nipped or disturbed"
    ],
    "staffNote": "",
    "headerSummary": "Roomy algae grazer with calm behavior and venomous dorsal spines. Room and spine safety both matter as much as algae utility.",
    "behavior": "Steady algae grazer with a calm overall presence and long grazing passes across rock and glass. Rabbitfish are usually easier community additions than they look, but they still need room and deserve respect because of their venomous dorsal spines.",
    "feedingNotes": "Make algae support part of the routine, not an afterthought. Seaweed sheets, herbivore pellets, and occasional frozen rotation usually keep rabbitfish in better long-term condition.",
    "buyingGuidance": "A strong recommendation when the buyer wants algae help and a larger peaceful display fish, but the conversation should still include spine caution and the need for long-term room.",
    "recognitionNotes": "Look for the foxface/rabbitfish body shape, browsing behavior, and dorsal spines."
  },
  {
    "id": "foxface-rabbitfish",
    "name": "Foxface Rabbitfish",
    "name_es": "Pez Conejo Cara de Zorro",
    "scientific": "Siganus vulpinus",
    "category": "Rabbitfish",
    "type": "Saltwater Fish",
    "aggression": 30,
    "coralRisk": 10,
    "invertRisk": 5,
    "careDifficulty": 25,
    "diet": "Herbivore",
    "diet_es": "Herbívoro",
    "origin": "Western Pacific",
    "origin_es": "Pacífico Occidental",
    "habitat": "Coral reefs",
    "maxSize": "10 in",
    "minTank": "100+ gal",
    "photoTitle": "Siganus_vulpinus",
    "role": "Yellow herbivore with venomous spines",
    "role_es": "Herbívoro amarillo con espinas venenosas",
    "overview": "Vibrant yellow with black and white face. Excellent algae grazer with venomous dorsal spines. Hardy and peaceful.",
    "overview_es": "Amarillo vibrante con cara blanca y negra. Excelente comedor de algas con espinas venenosas.",
    "inStock": false,
    "price": 0,
    "stockSize": "",
    "tankCode": "",
    "badges": [],
    "aliases": [],
    "facts": [
      "Adult size in this catalog is listed around 10 in.",
      "Plan around roughly 100+ gal or larger for long-term care.",
      "Diet in this catalog: Herbivore."
    ],
    "water": {
      "ph": [
        8,
        8.4
      ],
      "salinity": [
        1.023,
        1.026
      ],
      "temp": [
        75,
        80
      ],
      "ph_low": null,
      "ph_high": null,
      "sal_low": null,
      "sal_high": null,
      "temp_low": null,
      "temp_high": null
    },
    "seasonal": null,
    "careLabel": "Moderate",
    "visualCue": "Look for the foxface/rabbitfish body shape, browsing behavior, and dorsal spines.",
    "bestWith": [
      "Mature systems that meet the minimum tank size",
      "Reef-safe community plans with compatible tankmates",
      "Semi-aggressive tankmates of similar size"
    ],
    "cautionWith": [
      "Tankmates that do not match its adult size or activity level",
      "Systems smaller than 100+ gal"
    ],
    "staffNote": "",
    "headerSummary": "Yellow herbivore with venomous spines. Plan on roughly 100+ gal or larger long term.",
    "behavior": "Steady algae grazer with a calm overall presence and long grazing passes across rock and glass. Rabbitfish are usually easier community additions than they look, but they still need room and deserve respect because of their venomous dorsal spines.",
    "feedingNotes": "Make algae support part of the routine, not an afterthought. Seaweed sheets, herbivore pellets, and occasional frozen rotation usually keep rabbitfish in better long-term condition.",
    "buyingGuidance": "A strong recommendation when the buyer wants algae help and a larger peaceful display fish, but the conversation should still include spine caution and the need for long-term room.",
    "recognitionNotes": "Look for the foxface/rabbitfish body shape, browsing behavior, and dorsal spines."
  }
];
