window.LTC_SPECIES_CHUNKS = window.LTC_SPECIES_CHUNKS || {};
window.LTC_SPECIES_CHUNKS["Urchins"] = [
  {
    "id": "tuxedo-urchin",
    "name": "Tuxedo Urchin",
    "aliases": [
      "Pincushion Urchin",
      "Blue Tuxedo Urchin"
    ],
    "scientific": "Mespilia globulus",
    "category": "Urchins",
    "type": "Invertebrate",
    "price": 0,
    "stockSize": "",
    "maxSize": "3 in",
    "minTank": "20+ gal",
    "careLabel": "Easy",
    "diet": "Herbivore",
    "origin": "Indo-Pacific",
    "habitat": "Reef flats and algae-covered rubble",
    "tankCode": "",
    "aggression": 4,
    "coralRisk": 4,
    "invertRisk": 2,
    "careDifficulty": 14,
    "role": "Decorative algae-eating urchin that wears debris",
    "visualCue": "Blue and black banded body. Picks up shells, rubble, and coral frags to wear as camouflage.",
    "overview": "A highly effective algae eater that also provides entertainment — it picks up loose items and carries them around as decoration. Kids and adults both love watching it.",
    "facts": [
      "Picks up and wears loose items — frags, shells, rocks.",
      "Very effective algae grazer.",
      "The carrying behavior is a major selling point."
    ],
    "bestWith": [
      "Any reef tank with algae",
      "Families with kids — the carrying behavior is fascinating",
      "Established tanks"
    ],
    "cautionWith": [
      "Loose coral frags it might carry off and knock over",
      "Tanks with zero algae — it will starve"
    ],
    "staffNote": "Show customers the carrying behavior. It's the selling point.",
    "photoTitle": "Mespilia globulus",
    "inStock": false,
    "badges": [],
    "water": {
      "ph_low": 8.1,
      "ph_high": 8.4,
      "sal_low": 1.024,
      "sal_high": 1.026,
      "temp_low": 76,
      "temp_high": 80
    },
    "name_es": "Erizo Esmoquin",
    "overview_es": "Un comedor de algas efectivo que también entretiene — recoge objetos sueltos y los lleva como decoración.",
    "role_es": "Erizo comedor de algas que carga objetos",
    "diet_es": "Herbívoro",
    "origin_es": "Indo-Pacífico",
    "headerSummary": "Decorative algae-eating urchin that wears debris. Look for blue and black banded body. Picks up shells, rubble, and coral frags to wear as camouflage. Plan on at least 20+ gal.",
    "seasonal": null
  },
  {
    "id": "collector-urchin",
    "name": "Collector Urchin",
    "name_es": "Collector Urchin",
    "aliases": [],
    "scientific": "Tripneustes gratilla",
    "category": "Urchins",
    "type": "Saltwater Invert",
    "price": 0,
    "stockSize": "",
    "maxSize": "4 in",
    "minTank": "30+ gal",
    "diet": "Herbivore",
    "diet_es": "",
    "origin": "Indo-Pacific",
    "origin_es": "",
    "habitat": "Algae-rich reef flats and rubble zones",
    "tankCode": "",
    "aggression": 0,
    "coralRisk": 4,
    "invertRisk": 0,
    "careDifficulty": 24,
    "role": "Active algae urchin that loves to carry shells, rubble, and loose frags as camouflage",
    "role_es": "",
    "overview": "A strong algae grazer with the classic urchin habit of decorating itself with whatever it can grab. Great when the buyer enjoys that behavior and has a tank that can tolerate a little harmless rearranging.",
    "overview_es": "",
    "facts": [
      "Will carry shells, rubble, and sometimes loose coral frags.",
      "Needs ongoing algae or supplemental grazing support in clean tanks.",
      "Safer with secure frags and stable rockwork."
    ],
    "photoTitle": "Tripneustes gratilla",
    "inStock": false,
    "badges": [],
    "water": {
      "ph_low": 8,
      "ph_high": 8.4,
      "sal_low": 1.024,
      "sal_high": 1.026,
      "temp_low": 75,
      "temp_high": 80
    },
    "seasonal": null,
    "careLabel": "Intermediate",
    "visualCue": "round urchin body often hidden under a pile of shells, rubble, or coral plugs it has collected.",
    "bestWith": [
      "Established algae-bearing reefs",
      "Customers who like visible odd behavior",
      "Rockwork with stable footing"
    ],
    "cautionWith": [
      "Loose frags and unsecured plugs",
      "Ultra-clean sterile systems",
      "Tiny tanks where an urchin quickly becomes oversized"
    ],
    "staffNote": "Good algae worker. Just warn buyers that it will redecorate with loose objects.",
    "headerSummary": "Active algae urchin that loves to carry shells, rubble, and loose frags as camouflage. Look for round urchin body often hidden under a pile of shells, rubble, or coral plugs it has collected. Plan on at least 30+ gal."
  },
  {
    "id": "halloween-urchin",
    "name": "Halloween Urchin",
    "name_es": "Halloween Urchin",
    "aliases": [],
    "scientific": "Tripneustes gratilla",
    "category": "Urchins",
    "type": "Saltwater Invert",
    "price": 0,
    "stockSize": "",
    "maxSize": "4 in",
    "minTank": "30+ gal",
    "diet": "Herbivore",
    "diet_es": "",
    "origin": "Indo-Pacific",
    "origin_es": "",
    "habitat": "Reef flats and algae-covered rubble",
    "tankCode": "",
    "aggression": 0,
    "coralRisk": 4,
    "invertRisk": 0,
    "careDifficulty": 24,
    "role": "Colorful algae-eating urchin with the same debris-carrying habits that make urchins fun and annoying",
    "role_es": "",
    "overview": "Sold mainly for color plus cleanup value. Like other carrying urchins, it needs buyers who can laugh when a loose frag plug goes for a walk instead of assuming the tank will stay untouched.",
    "overview_es": "",
    "facts": [
      "Strong grazer on algae and films over hard surfaces.",
      "Will pick up loose items and wear them as cover.",
      "Needs a mature tank with real food available."
    ],
    "photoTitle": "Tripneustes gratilla",
    "inStock": false,
    "badges": [],
    "water": {
      "ph_low": 8,
      "ph_high": 8.4,
      "sal_low": 1.024,
      "sal_high": 1.026,
      "temp_low": 75,
      "temp_high": 80
    },
    "seasonal": null,
    "careLabel": "Intermediate",
    "visualCue": "orange to reddish body accents and short decorative spines, often partly covered with shells or rubble.",
    "bestWith": [
      "Established mixed reefs",
      "Customers who want a colorful urchin",
      "Tanks with secure coral placement"
    ],
    "cautionWith": [
      "Brand-new tanks",
      "Unsecured frags and decorative rubble",
      "Customers wanting a hands-off precision cleanup animal"
    ],
    "staffNote": "Very saleable if the buyer likes urchin behavior and has secure frags.",
    "headerSummary": "Colorful algae-eating urchin with the same debris-carrying habits that make urchins fun and annoying. Look for orange to reddish body accents and short decorative spines, often partly covered with shells or rubble. Plan on at least 30+ gal."
  },
  {
    "id": "long-spine-urchin",
    "name": "Long Spine Urchin",
    "name_es": "Long Spine Urchin",
    "aliases": [],
    "scientific": "Diadema setosum",
    "category": "Urchins",
    "type": "Saltwater Invert",
    "price": 0,
    "stockSize": "",
    "maxSize": "8 in body / much larger span",
    "minTank": "75+ gal",
    "diet": "Herbivore",
    "diet_es": "Herbívoro / algas",
    "origin": "Indo-Pacific",
    "origin_es": "Indo-Pacífico",
    "habitat": "Open reef faces and rock crevices",
    "tankCode": "",
    "aggression": 0,
    "coralRisk": 2,
    "invertRisk": 0,
    "careDifficulty": 34,
    "role": "High-capacity algae grazer with dramatic long spines that demands real space and careful handling",
    "role_es": "Erizo clásico de espinas largas negras para control de algas",
    "overview": "A powerful grazer, but not a casual nano-reef purchase. This is for customers with room, respect for the spines, and a tank layout that will not turn every pass into a collision event.",
    "overview_es": "El icónico erizo de mar de espinas largas. Extremadamente efectivo comedor de algas pero las espinas venenosas pueden picar.",
    "facts": [
      "Excellent grazer on algae and open rock surfaces.",
      "Spines are long, sharp, and easy to bump during maintenance.",
      "Needs larger tanks with enough footprint for safe movement."
    ],
    "photoTitle": "Diadema setosum",
    "inStock": false,
    "badges": [],
    "water": {
      "ph_low": 8,
      "ph_high": 8.4,
      "sal_low": 1.024,
      "sal_high": 1.026,
      "temp_low": 75,
      "temp_high": 80
    },
    "seasonal": null,
    "careLabel": "Intermediate",
    "visualCue": "black body with extremely long needle-like spines that radiate far beyond the shell.",
    "bestWith": [
      "Larger algae-bearing reefs",
      "Experienced keepers",
      "Open rock layouts with stable placement"
    ],
    "cautionWith": [
      "Tight nano rockwork",
      "Careless maintenance around long spines",
      "Expecting a cute decorative urchin instead of a serious grazer"
    ],
    "staffNote": "Make the buyer picture the actual spine span before they buy it.",
    "headerSummary": "High-capacity algae grazer with dramatic long spines that demands real space and careful handling. Look for black body with extremely long needle-like spines that radiate far beyond the shell. Plan on at least 75+ gal."
  },
  {
    "id": "pencil-urchin",
    "name": "Pencil Urchin",
    "name_es": "Pencil Urchin",
    "aliases": [],
    "scientific": "Eucidaris tribuloides",
    "category": "Urchins",
    "type": "Saltwater Invert",
    "price": 0,
    "stockSize": "",
    "maxSize": "5 in",
    "minTank": "75+ gal",
    "diet": "Omnivore / grazer",
    "diet_es": "",
    "origin": "Caribbean / tropical western Atlantic",
    "origin_es": "",
    "habitat": "Rock and rubble zones",
    "tankCode": "",
    "aggression": 0,
    "coralRisk": 22,
    "invertRisk": 4,
    "careDifficulty": 32,
    "role": "Chunky urchin better suited to fishy mixed systems than to delicate reef-frag displays",
    "role_es": "",
    "overview": "Very cool-looking urchin, but one that deserves a more cautious sales pitch than tuxedo or carrying species. Pencil urchins can bulldoze, rasp surfaces, and generally act like a bigger rougher animal in the tank.",
    "overview_es": "",
    "facts": [
      "Thicker spines make it more of a bulldozer around loose items.",
      "May rasp encrusting surfaces and bother delicate sessile life while grazing.",
      "Best sold into tanks with room and realistic expectations."
    ],
    "photoTitle": "Eucidaris tribuloides",
    "inStock": false,
    "badges": [],
    "water": {
      "ph_low": 8,
      "ph_high": 8.4,
      "sal_low": 1.024,
      "sal_high": 1.026,
      "temp_low": 75,
      "temp_high": 80
    },
    "seasonal": null,
    "careLabel": "Intermediate",
    "visualCue": "thick blunt pencil-like spines that make it look heavier and rougher than tuxedo-style urchins.",
    "bestWith": [
      "Larger fishy reef systems",
      "Rocky tanks with natural algae",
      "Oddball invert collections"
    ],
    "cautionWith": [
      "High-end frag gardens",
      "Tiny reefs with delicate placement",
      "Customers assuming every urchin is equally reef gentle"
    ],
    "staffNote": "Cool animal, just not the safest urchin for delicate coral displays.",
    "headerSummary": "Chunky urchin better suited to fishy mixed systems than to delicate reef-frag displays. Look for thick blunt pencil-like spines that make it look heavier and rougher than tuxedo-style urchins. Plan on at least 75+ gal."
  },
  {
    "id": "pin-cushion-urchin",
    "name": "Pin Cushion Urchin",
    "name_es": "Pin Cushion Urchin",
    "aliases": [],
    "scientific": "Lytechinus variegatus",
    "category": "Urchins",
    "type": "Saltwater Invert",
    "price": 0,
    "stockSize": "",
    "maxSize": "4 in",
    "minTank": "30+ gal",
    "diet": "Herbivore",
    "diet_es": "",
    "origin": "Caribbean / tropical western Atlantic",
    "origin_es": "",
    "habitat": "Reef flats and rubble",
    "tankCode": "",
    "aggression": 0,
    "coralRisk": 4,
    "invertRisk": 0,
    "careDifficulty": 22,
    "role": "Classic round grazing urchin for established tanks with stable algae supply",
    "role_es": "",
    "overview": "A dependable algae urchin for customers who want more grazing power than snails provide. It still needs the usual urchin conversation about mature tanks, secure frags, and enough natural food.",
    "overview_es": "",
    "facts": [
      "Useful grazer on algae and films over hard surfaces.",
      "May carry or nudge loose items while moving.",
      "Needs ongoing food support once nuisance algae drops."
    ],
    "photoTitle": "Lytechinus variegatus",
    "inStock": false,
    "badges": [],
    "water": {
      "ph_low": 8,
      "ph_high": 8.4,
      "sal_low": 1.024,
      "sal_high": 1.026,
      "temp_low": 75,
      "temp_high": 80
    },
    "seasonal": null,
    "careLabel": "Intermediate",
    "visualCue": "dense even spine coverage that gives the classic pincushion silhouette.",
    "bestWith": [
      "Established algae-bearing tanks",
      "Mixed cleanup crews needing more muscle",
      "Customers comfortable with urchin behavior"
    ],
    "cautionWith": [
      "Ultra-clean tanks",
      "Loose frags and unsecured plugs",
      "Very small systems"
    ],
    "staffNote": "Good middle-ground urchin sale when the tank is mature enough.",
    "headerSummary": "Classic round grazing urchin for established tanks with stable algae supply. Look for dense even spine coverage that gives the classic pincushion silhouette. Plan on at least 30+ gal."
  },
  {
    "id": "short-spine-urchin",
    "name": "Short Spine Urchin",
    "name_es": "Short Spine Urchin",
    "aliases": [],
    "scientific": "Echinometra sp.",
    "category": "Urchins",
    "type": "Saltwater Invert",
    "price": 0,
    "stockSize": "",
    "maxSize": "3 in",
    "minTank": "30+ gal",
    "diet": "Herbivore",
    "diet_es": "",
    "origin": "Indo-Pacific",
    "origin_es": "",
    "habitat": "Rock crevices and rubble zones",
    "tankCode": "",
    "aggression": 0,
    "coralRisk": 6,
    "invertRisk": 0,
    "careDifficulty": 24,
    "role": "Compact rock-grazing urchin that still needs mature algae support and secure decor",
    "role_es": "",
    "overview": "A more compact urchin option, but still not a beginner impulse purchase for sterile new tanks. Best sold into mature systems where the buyer already understands that urchins need food after the first algae wave fades.",
    "overview_es": "",
    "facts": [
      "Good grazer on rock surfaces and coralline-covered areas.",
      "Often hides in crevices when not actively feeding.",
      "Can still move loose items despite the shorter spines."
    ],
    "photoTitle": "Echinometra",
    "inStock": false,
    "badges": [],
    "water": {
      "ph_low": 8,
      "ph_high": 8.4,
      "sal_low": 1.024,
      "sal_high": 1.026,
      "temp_low": 75,
      "temp_high": 80
    },
    "seasonal": null,
    "careLabel": "Intermediate",
    "visualCue": "short tighter spine coverage and a habit of wedging into rock crevices between grazing runs.",
    "bestWith": [
      "Mature reef tanks",
      "Rocky layouts with crevices",
      "Customers wanting a smaller urchin profile"
    ],
    "cautionWith": [
      "New tanks with little algae",
      "Loose coral frags",
      "Buyers who think smaller means no special considerations"
    ],
    "staffNote": "Smaller footprint than long-spine species, same need for a mature tank.",
    "headerSummary": "Compact rock-grazing urchin that still needs mature algae support and secure decor. Look for short tighter spine coverage and a habit of wedging into rock crevices between grazing runs. Plan on at least 30+ gal."
  },
  {
    "id": "sand-dollar",
    "name": "Sand Dollar",
    "name_es": "Dólar de Arena",
    "scientific": "Clypeaster reticulatus",
    "category": "Urchins",
    "type": "Invertebrate",
    "aggression": 2,
    "coralRisk": 2,
    "invertRisk": 2,
    "careDifficulty": 60,
    "diet": "Detritivore",
    "diet_es": "Detritívoro",
    "origin": "Caribbean",
    "origin_es": "Caribe",
    "habitat": "Sandy bottoms",
    "maxSize": "4 in",
    "minTank": "50+ gal",
    "photoTitle": "Clypeaster_reticulatus",
    "role": "Flat burrowing echinoderm",
    "role_es": "Equinodermo plano excavador",
    "overview": "Sand dollars burrow through substrate processing organic matter. Need deep sand bed. Not for beginners.",
    "overview_es": "Excavan a través del sustrato procesando materia orgánica. Necesitan lecho de arena profundo.",
    "inStock": false,
    "price": 0,
    "stockSize": "",
    "tankCode": "",
    "badges": [],
    "aliases": [],
    "facts": [
      "Adult size in this catalog is listed around 4 in.",
      "Plan around roughly 50+ gal or larger for long-term care.",
      "Diet in this catalog: Detritivore."
    ],
    "water": {
      "ph": [
        8,
        8.4
      ],
      "salinity": [
        1.023,
        1.026
      ],
      "temp": [
        75,
        80
      ],
      "ph_low": null,
      "ph_high": null,
      "sal_low": null,
      "sal_high": null,
      "temp_low": null,
      "temp_high": null
    },
    "seasonal": null,
    "careLabel": "Intermediate",
    "visualCue": "Look for spine length, spine density, and whether it carries debris or grazes exposed surfaces.",
    "bestWith": [
      "Stable systems with mature parameters",
      "Tankmates unlikely to harass or overturn invertebrates",
      "Reef tanks planned around its specific role"
    ],
    "cautionWith": [
      "Unstable salinity, immature systems, or rough handling",
      "Fish known to nip, flip, or harass small invertebrates"
    ],
    "staffNote": "Confirm placement, tank maturity, and specific feeding needs before sale. Treat this as a intermediate invertebrate profile, not a generic add-on.",
    "headerSummary": "Flat burrowing echinoderm. Plan on roughly 50+ gal or larger long term.",
    "behavior": "Temperament is usually workable in a well-planned community with sensible tankmates.",
    "feedingNotes": "Match the food size and routine to the actual species instead of relying only on the category label. Catalog diet listing: Detritivore.",
    "buyingGuidance": "Match the sale to long-term size, feeding pattern, and compatibility instead of impulse color.",
    "recognitionNotes": "Look for spine length, spine density, and whether it carries debris or grazes exposed surfaces."
  },
  {
    "id": "blue-tuxedo-urchin",
    "name": "Blue Tuxedo Urchin",
    "name_es": "Erizo Esmoquin Azul",
    "scientific": "Mespilia globulus",
    "category": "Urchins",
    "type": "Invertebrate",
    "aggression": 3,
    "coralRisk": 5,
    "invertRisk": 3,
    "careDifficulty": 15,
    "diet": "Herbivore",
    "diet_es": "Herbívoro",
    "origin": "Indo-Pacific",
    "origin_es": "Indo-Pacífico",
    "habitat": "Reef flats",
    "maxSize": "3 in",
    "minTank": "20+ gal",
    "photoTitle": "Mespilia_globulus",
    "role": "Colorful urchin that carries decorations",
    "role_es": "Erizo colorido que carga decoraciones",
    "overview": "Blue and orange-red bands. Picks up objects and carries them. Excellent algae grazer.",
    "overview_es": "Bandas azules y rojo-naranja. Recoge objetos y los carga. Excelente comedor de algas.",
    "inStock": false,
    "price": 0,
    "stockSize": "",
    "tankCode": "",
    "badges": [],
    "aliases": [],
    "facts": [
      "Adult size in this catalog is listed around 3 in.",
      "Plan around roughly 20+ gal or larger for long-term care.",
      "Diet in this catalog: Herbivore."
    ],
    "water": {
      "ph": [
        8,
        8.4
      ],
      "salinity": [
        1.023,
        1.026
      ],
      "temp": [
        75,
        80
      ],
      "ph_low": null,
      "ph_high": null,
      "sal_low": null,
      "sal_high": null,
      "temp_low": null,
      "temp_high": null
    },
    "seasonal": null,
    "careLabel": "Easy",
    "visualCue": "Look for spine length, spine density, and whether it carries debris or grazes exposed surfaces.",
    "bestWith": [
      "Stable systems with mature parameters",
      "Tankmates unlikely to harass or overturn invertebrates",
      "Reef tanks planned around its specific role"
    ],
    "cautionWith": [
      "Unstable salinity, immature systems, or rough handling",
      "Fish known to nip, flip, or harass small invertebrates"
    ],
    "staffNote": "Confirm placement, tank maturity, and specific feeding needs before sale. Treat this as a easy invertebrate profile, not a generic add-on.",
    "headerSummary": "Colorful urchin that carries decorations. Plan on roughly 20+ gal or larger long term.",
    "behavior": "Temperament is usually workable in a well-planned community with sensible tankmates.",
    "feedingNotes": "Match the food size and routine to the actual species instead of relying only on the category label. Catalog diet listing: Herbivore.",
    "buyingGuidance": "Match the sale to long-term size, feeding pattern, and compatibility instead of impulse color.",
    "recognitionNotes": "Look for spine length, spine density, and whether it carries debris or grazes exposed surfaces."
  }
];
