window.LTC_SPECIES_CHUNKS = window.LTC_SPECIES_CHUNKS || {};
window.LTC_SPECIES_CHUNKS["Other Fish"] = [
  {
    "id": "purple-firefish",
    "name": "Purple Firefish",
    "aliases": [
      "Elegant Firefish",
      "Decorated Firefish"
    ],
    "scientific": "Nemateleotris decora",
    "category": "Other Fish",
    "type": "Saltwater Fish",
    "price": 0,
    "stockSize": "",
    "maxSize": "4 in",
    "minTank": "20+ gal",
    "careLabel": "Easy",
    "diet": "Carnivore",
    "origin": "Indo-Pacific",
    "habitat": "Outer reef slopes with current",
    "tankCode": "",
    "aggression": 10,
    "coralRisk": 2,
    "invertRisk": 4,
    "careDifficulty": 22,
    "role": "Elegant hovering firefish with purple and orange coloration",
    "visualCue": "White front grading to purple and orange at the rear, with an elongated dorsal fin that flicks like a flag.",
    "overview": "A more colorful cousin of the common Firefish. The purple and orange gradient is stunning, and the dorsal fin flicking behavior is mesmerizing.",
    "facts": [
      "More expensive than the common Red Firefish but worth it.",
      "Very shy — needs hiding spots and calm tankmates.",
      "The dorsal fin flicking behavior is distinctive."
    ],
    "bestWith": [
      "Peaceful reef tanks",
      "Tanks with overhangs and bolt holes",
      "Calm communities"
    ],
    "cautionWith": [
      "Aggressive tankmates",
      "Open-top tanks — they jump",
      "Very crowded tanks with no hiding spots"
    ],
    "staffNote": "Gorgeous but shy. Needs the right tankmates to thrive and be visible.",
    "photoTitle": "Nemateleotris decora",
    "inStock": false,
    "badges": [],
    "water": {
      "ph_low": 8,
      "ph_high": 8.4,
      "sal_low": 1.024,
      "sal_high": 1.026,
      "temp_low": 75,
      "temp_high": 80
    },
    "name_es": "Pez de Fuego Púrpura",
    "overview_es": "Un primo más colorido del Pez de Fuego común. El degradado púrpura y naranja es impresionante.",
    "role_es": "Pez de fuego elegante con coloración púrpura y naranja",
    "diet_es": "Carnívoro",
    "origin_es": "Indo-Pacífico",
    "headerSummary": "Elegant hovering firefish with purple and orange coloration. Look for white front grading to purple and orange at the rear, with an elongated dorsal fin that flicks like a flag. Plan on at least 20+ gal.",
    "seasonal": null
  },
  {
    "id": "red-firefish",
    "name": "Red Firefish",
    "aliases": [
      "Firefish Goby",
      "Fire Dartfish"
    ],
    "scientific": "Nemateleotris magnifica",
    "category": "Other Fish",
    "type": "Saltwater Fish",
    "price": 0,
    "stockSize": "",
    "maxSize": "3.5 in",
    "minTank": "20+ gal",
    "careLabel": "Easy",
    "diet": "Carnivore",
    "origin": "Indo-Pacific",
    "habitat": "Outer reef slopes",
    "tankCode": "",
    "aggression": 8,
    "coralRisk": 2,
    "invertRisk": 4,
    "careDifficulty": 18,
    "role": "Classic affordable firefish for any reef",
    "visualCue": "White body grading to red-orange at the tail, with a tall dorsal fin that flicks constantly.",
    "overview": "One of the most popular and affordable reef fish. The white-to-red gradient, hovering behavior, and dorsal fin flicking make it endlessly entertaining.",
    "facts": [
      "One of the best beginner reef fish available.",
      "Very affordable — great entry-level purchase.",
      "Needs a lid — notorious jumper."
    ],
    "bestWith": [
      "Any peaceful reef tank",
      "Beginners",
      "Budget-friendly setups"
    ],
    "cautionWith": [
      "Open-top tanks",
      "Aggressive fast-moving fish",
      "Already having a firefish — they fight with their own kind"
    ],
    "staffNote": "The beginner reef fish. Cheap, pretty, easy, and always available.",
    "photoTitle": "Nemateleotris magnifica",
    "inStock": false,
    "badges": [],
    "water": {
      "ph_low": 8,
      "ph_high": 8.4,
      "sal_low": 1.024,
      "sal_high": 1.026,
      "temp_low": 75,
      "temp_high": 80
    },
    "name_es": "Pez de Fuego Rojo",
    "overview_es": "Uno de los peces de arrecife más populares y económicos. El degradado blanco a rojo y el aleteo dorsal son entretenidos.",
    "role_es": "Pez de fuego clásico y económico para cualquier arrecife",
    "diet_es": "Carnívoro",
    "origin_es": "Indo-Pacífico",
    "headerSummary": "Classic affordable firefish for any reef. Look for white body grading to red-orange at the tail, with a tall dorsal fin that flicks constantly. Plan on at least 20+ gal.",
    "seasonal": null
  },
  {
    "id": "chalk-bass",
    "name": "Chalk Bass",
    "aliases": [
      "Chalk Basslet"
    ],
    "scientific": "Serranus tortugarum",
    "category": "Other Fish",
    "type": "Saltwater Fish",
    "price": 0,
    "stockSize": "",
    "maxSize": "3 in",
    "minTank": "20+ gal",
    "careLabel": "Easy",
    "diet": "Carnivore",
    "origin": "Caribbean",
    "habitat": "Rocky reef walls and rubble areas",
    "tankCode": "",
    "aggression": 18,
    "coralRisk": 2,
    "invertRisk": 6,
    "careDifficulty": 14,
    "role": "Hardy affordable basslet that can be kept in groups",
    "visualCue": "Pale lavender-blue body with faint vertical bars and an orange-pink belly.",
    "overview": "An underappreciated gem that tolerates beginner mistakes well. Can be kept in small groups unlike most basslets, and the pale lavender color is subtle but attractive.",
    "facts": [
      "One of the hardiest small marine fish available.",
      "Can keep multiple together if introduced simultaneously.",
      "Very affordable — great for filling out a community."
    ],
    "bestWith": [
      "Beginner tanks",
      "Small groups introduced together",
      "Community reef setups"
    ],
    "cautionWith": [
      "Adding new ones to an established group — introduce all at once"
    ],
    "staffNote": "Extremely hardy, very cheap. The beginner safety net fish.",
    "photoTitle": "Serranus tortugarum",
    "inStock": false,
    "badges": [],
    "water": {
      "ph_low": 8,
      "ph_high": 8.4,
      "sal_low": 1.024,
      "sal_high": 1.026,
      "temp_low": 75,
      "temp_high": 80
    },
    "name_es": "Bajo Tiza",
    "overview_es": "Una joya subestimada que tolera errores de principiante. Puede mantenerse en grupos pequeños y es muy económico.",
    "role_es": "Bajo resistente y económico que se mantiene en grupos",
    "diet_es": "Carnívoro",
    "origin_es": "Caribe",
    "headerSummary": "Hardy affordable basslet that can be kept in groups. Look for pale lavender-blue body with faint vertical bars and an orange-pink belly. Plan on at least 20+ gal.",
    "seasonal": null
  },
  {
    "id": "cockatoo-waspfish",
    "name": "Cockatoo Waspfish",
    "name_es": "Cockatoo Waspfish",
    "aliases": [],
    "scientific": "Ablabys taenianotus",
    "category": "Other Fish",
    "type": "Saltwater Fish",
    "price": 0,
    "stockSize": "",
    "maxSize": "5 in",
    "minTank": "30+ gal",
    "diet": "Carnivore",
    "diet_es": "",
    "origin": "Unknown",
    "origin_es": "",
    "habitat": "Reef / rocky",
    "tankCode": "",
    "aggression": 38,
    "coralRisk": 28,
    "invertRisk": 20,
    "careDifficulty": 56,
    "role": "Cryptic ambush fish kept for oddball appeal rather than nonstop swimming",
    "role_es": "",
    "overview": "Cockatoo Waspfish is a cryptic oddball kept more for subtle ambush behavior than nonstop swimming. The catalog lists a minimum tank around 30+ gal. Adult size is listed around 5 in. Diet here is listed as Carnivore.",
    "overview_es": "",
    "facts": [
      "Adult size in this catalog is listed around 5 in.",
      "Plan around roughly 30+ gal or larger for long-term care.",
      "Diet in this catalog: Carnivore."
    ],
    "photoTitle": "Cockatoo Waspfish",
    "inStock": false,
    "badges": [],
    "water": {
      "ph_low": 8,
      "ph_high": 8.4,
      "sal_low": 1.024,
      "sal_high": 1.026,
      "temp_low": 75,
      "temp_high": 80
    },
    "seasonal": null,
    "careLabel": "Intermediate",
    "visualCue": "Look for a cryptic outline, perching posture, and camouflage that breaks up the body shape.",
    "bestWith": [
      "Mature systems that meet the minimum tank size",
      "Tankmates chosen around its behavior and adult size",
      "Semi-aggressive tankmates of similar size"
    ],
    "cautionWith": [
      "Tankmates that do not match its adult size or activity level",
      "Corals or polyps that could be nipped or disturbed"
    ],
    "staffNote": "",
    "headerSummary": "Cryptic ambush fish kept for oddball appeal rather than nonstop swimming. Plan on roughly 30+ gal or larger long term.",
    "behavior": "Often perches and waits instead of swimming constantly. Best appreciated by buyers who enjoy subtle behavior, not nonstop motion.",
    "feedingNotes": "Needs meaty foods and often does better when target-fed in a calm low-competition setup.",
    "recognitionNotes": "Look for the odd contour and stillness—this fish hides by looking like part of the scenery.",
    "buyingGuidance": "Sell to buyers who appreciate unusual predatory fish and understand that cryptic behavior is the point, not a flaw."
  },
  {
    "id": "leaf-fish",
    "name": "Leaf Fish",
    "name_es": "Leaf Fish",
    "aliases": [],
    "scientific": "Taenianotus triacanthus",
    "category": "Other Fish",
    "type": "Saltwater Fish",
    "price": 0,
    "stockSize": "",
    "maxSize": "4 in",
    "minTank": "30+ gal",
    "diet": "Carnivore",
    "diet_es": "",
    "origin": "Unknown",
    "origin_es": "",
    "habitat": "Reef / rocky",
    "tankCode": "",
    "aggression": 38,
    "coralRisk": 28,
    "invertRisk": 20,
    "careDifficulty": 56,
    "role": "Cryptic ambush fish kept for oddball appeal rather than nonstop swimming",
    "role_es": "",
    "overview": "Leaf Fish is a cryptic oddball kept more for subtle ambush behavior than nonstop swimming. The catalog lists a minimum tank around 30+ gal. Adult size is listed around 4 in. Diet here is listed as Carnivore.",
    "overview_es": "",
    "facts": [
      "Adult size in this catalog is listed around 4 in.",
      "Plan around roughly 30+ gal or larger for long-term care.",
      "Diet in this catalog: Carnivore."
    ],
    "photoTitle": "Leaf Fish",
    "inStock": false,
    "badges": [],
    "water": {
      "ph_low": 8,
      "ph_high": 8.4,
      "sal_low": 1.024,
      "sal_high": 1.026,
      "temp_low": 75,
      "temp_high": 80
    },
    "seasonal": null,
    "careLabel": "Intermediate",
    "visualCue": "Look for a cryptic outline, perching posture, and camouflage that breaks up the body shape.",
    "bestWith": [
      "Mature systems that meet the minimum tank size",
      "Tankmates chosen around its behavior and adult size",
      "Semi-aggressive tankmates of similar size"
    ],
    "cautionWith": [
      "Tankmates that do not match its adult size or activity level",
      "Corals or polyps that could be nipped or disturbed"
    ],
    "staffNote": "",
    "headerSummary": "Cryptic ambush fish kept for oddball appeal rather than nonstop swimming. Plan on roughly 30+ gal or larger long term.",
    "behavior": "Mostly still, cryptic, and waiting. It rewards close observation rather than high-energy display behavior.",
    "feedingNotes": "Feed carefully with meaty foods and avoid tankmates that outcompete or stress it away from meals.",
    "recognitionNotes": "Leaf shape, slow drifting posture, and incredible camouflage are the whole appeal.",
    "buyingGuidance": "Best sold to advanced buyers building around unusual behavior, not around color or speed."
  },
  {
    "id": "aiptasia-eating-filefish",
    "name": "Aiptasia Eating Filefish",
    "name_es": "Aiptasia Eating Filefish",
    "aliases": [],
    "scientific": "Acreichthys tomentosus",
    "category": "Other Fish",
    "type": "Saltwater Fish",
    "price": 0,
    "stockSize": "",
    "maxSize": "5 in",
    "minTank": "30+ gal",
    "diet": "Omnivore",
    "diet_es": "",
    "origin": "Unknown",
    "origin_es": "",
    "habitat": "Reef / rocky",
    "tankCode": "",
    "aggression": 38,
    "coralRisk": 28,
    "invertRisk": 20,
    "careDifficulty": 42,
    "role": "Unusual display fish whose feeding behavior and compatibility need to be discussed first",
    "role_es": "",
    "overview": "Aiptasia Eating Filefish is an unusual display fish whose feeding habits and compatibility should be discussed honestly. The catalog lists a minimum tank around 30+ gal. Adult size is listed around 5 in. Diet here is listed as Omnivore.",
    "overview_es": "",
    "facts": [
      "Adult size in this catalog is listed around 5 in.",
      "Plan around roughly 30+ gal or larger for long-term care.",
      "Diet in this catalog: Omnivore."
    ],
    "photoTitle": "Aiptasia Eating Filefish",
    "inStock": false,
    "badges": [],
    "water": {
      "ph_low": 8,
      "ph_high": 8.4,
      "sal_low": 1.024,
      "sal_high": 1.026,
      "temp_low": 75,
      "temp_high": 80
    },
    "seasonal": null,
    "careLabel": "Intermediate",
    "visualCue": "Look for a laterally compressed body, pointed snout, and deliberate stop-start swimming.",
    "bestWith": [
      "Mature systems that meet the minimum tank size",
      "Tankmates chosen around its behavior and adult size",
      "Semi-aggressive tankmates of similar size"
    ],
    "cautionWith": [
      "Tankmates that do not match its adult size or activity level",
      "Corals or polyps that could be nipped or disturbed"
    ],
    "staffNote": "",
    "headerSummary": "Unusual display fish whose feeding behavior and compatibility need to be discussed first. Plan on roughly 30+ gal or larger long term.",
    "behavior": "Usually calm and methodical, often picking around rockwork and problem areas.",
    "feedingNotes": "Even if it helps with Aiptasia, it still needs a dependable prepared-food routine for long-term success.",
    "recognitionNotes": "The pointed snout and slow deliberate picking behavior are the telltale signs.",
    "buyingGuidance": "A good sale when the buyer understands it is a useful pest-control tool, not a guaranteed coral-neutral miracle worker."
  },
  {
    "id": "comet",
    "name": "Comet",
    "name_es": "Comet",
    "aliases": [],
    "scientific": "Calloplesiops altivelis",
    "category": "Other Fish",
    "type": "Saltwater Fish",
    "price": 0,
    "stockSize": "",
    "maxSize": "8 in",
    "minTank": "55+ gal",
    "diet": "Carnivore",
    "diet_es": "",
    "origin": "Unknown",
    "origin_es": "",
    "habitat": "Reef / rocky",
    "tankCode": "",
    "aggression": 38,
    "coralRisk": 28,
    "invertRisk": 20,
    "careDifficulty": 42,
    "role": "Shy cave-oriented oddball with elegant finnage and slow, deliberate movement",
    "role_es": "",
    "overview": "Comet is a shy cave-oriented display fish that usually becomes more visible once it feels secure. The catalog lists a minimum tank around 55+ gal. Adult size is listed around 8 in. Diet here is listed as Carnivore.",
    "overview_es": "",
    "facts": [
      "Adult size in this catalog is listed around 8 in.",
      "Plan around roughly 55+ gal or larger for long-term care.",
      "Diet in this catalog: Carnivore."
    ],
    "photoTitle": "Comet",
    "inStock": false,
    "badges": [],
    "water": {
      "ph_low": 8,
      "ph_high": 8.4,
      "sal_low": 1.024,
      "sal_high": 1.026,
      "temp_low": 75,
      "temp_high": 80
    },
    "seasonal": null,
    "careLabel": "Intermediate",
    "visualCue": "Look for a dark cave fish with long finnage and bold ocellus-style markings.",
    "bestWith": [
      "Mature systems that meet the minimum tank size",
      "Tankmates chosen around its behavior and adult size",
      "Semi-aggressive tankmates of similar size"
    ],
    "cautionWith": [
      "Tankmates that do not match its adult size or activity level",
      "Corals or polyps that could be nipped or disturbed"
    ],
    "staffNote": "",
    "headerSummary": "Shy cave-oriented oddball with elegant finnage and slow, deliberate movement. Plan on roughly 55+ gal or larger long term.",
    "behavior": "Shy at first and often crepuscular, becoming more visible once secure caves and routine feeding are established.",
    "feedingNotes": "Feed meaty carnivore foods and give it protected feeding opportunities if tankmates are fast or aggressive.",
    "recognitionNotes": "The starry pattern and false eyespot are unmistakable once you know where to look.",
    "buyingGuidance": "A strong sale for buyers who value subtle, elegant display fish and understand that it may not sit front and center on day one."
  },
  {
    "id": "marine-betta",
    "name": "Marine Betta",
    "name_es": "Marine Betta",
    "aliases": [],
    "scientific": "Calloplesiops altivelis",
    "category": "Other Fish",
    "type": "Saltwater Fish",
    "price": 0,
    "stockSize": "",
    "maxSize": "8 in",
    "minTank": "55+ gal",
    "diet": "Carnivore",
    "diet_es": "Carnívoro",
    "origin": "Indo-Pacific",
    "origin_es": "Indo-Pacífico",
    "habitat": "Reef / rocky",
    "tankCode": "",
    "aggression": 20,
    "coralRisk": 5,
    "invertRisk": 25,
    "careDifficulty": 40,
    "role": "Shy cave-oriented oddball with elegant finnage and slow, deliberate movement",
    "role_es": "",
    "overview": "Dramatic black body covered in white spots with a false eyespot on the rear dorsal fin mimicking a moray eel. Shy predator.",
    "overview_es": "Cuerpo negro dramático cubierto de puntos blancos con un falso ojo en la aleta dorsal imitando una morena.",
    "facts": [
      "Adult size in this catalog is listed around 8 in.",
      "Plan around roughly 55+ gal or larger for long-term care.",
      "Diet in this catalog: Carnivore."
    ],
    "photoTitle": "Calloplesiops_altivelis",
    "inStock": false,
    "badges": [],
    "water": {
      "ph_low": 8,
      "ph_high": 8.4,
      "sal_low": 1.024,
      "sal_high": 1.026,
      "temp_low": 75,
      "temp_high": 80
    },
    "seasonal": null,
    "careLabel": "Intermediate",
    "visualCue": "Look for a dark cave fish with long finnage and bold ocellus-style markings.",
    "bestWith": [
      "Mature systems that meet the minimum tank size",
      "Reef-safe community plans with compatible tankmates",
      "Peaceful to semi-peaceful community livestock"
    ],
    "cautionWith": [
      "Tankmates that do not match its adult size or activity level",
      "Shrimp, snails, crabs, or other ornamental invertebrates",
      "Systems smaller than 55+ gal"
    ],
    "staffNote": "",
    "headerSummary": "Shy cave-oriented oddball with elegant finnage and slow, deliberate movement. Plan on roughly 55+ gal or larger long term.",
    "behavior": "Often shy at first and much more visible at dusk or after the tank has quieted down.",
    "feedingNotes": "Meaty foods offered in a calm low-competition setting are usually the easiest path to a reliable routine. Catalog diet listing: Carnivore.",
    "buyingGuidance": "A strong specialty sale for patient hobbyists who appreciate shy, elegant fish and are not expecting instant daytime center-stage behavior.",
    "recognitionNotes": "Look for the long dark fins and false eyespot pattern that make the fish look larger and harder to approach."
  },
  {
    "id": "matted-filefish",
    "name": "Matted Filefish",
    "name_es": "Matted Filefish",
    "aliases": [],
    "scientific": "Acreichthys tomentosus",
    "category": "Other Fish",
    "type": "Saltwater Fish",
    "price": 0,
    "stockSize": "",
    "maxSize": "5 in",
    "minTank": "30+ gal",
    "diet": "Omnivore",
    "diet_es": "",
    "origin": "Unknown",
    "origin_es": "",
    "habitat": "Reef / rocky",
    "tankCode": "",
    "aggression": 38,
    "coralRisk": 28,
    "invertRisk": 20,
    "careDifficulty": 42,
    "role": "Unusual display fish whose feeding behavior and compatibility need to be discussed first",
    "role_es": "",
    "overview": "Matted Filefish is an unusual display fish whose feeding habits and compatibility should be discussed honestly. The catalog lists a minimum tank around 30+ gal. Adult size is listed around 5 in. Diet here is listed as Omnivore.",
    "overview_es": "",
    "facts": [
      "Adult size in this catalog is listed around 5 in.",
      "Plan around roughly 30+ gal or larger for long-term care.",
      "Diet in this catalog: Omnivore."
    ],
    "photoTitle": "Matted Filefish",
    "inStock": false,
    "badges": [],
    "water": {
      "ph_low": 8,
      "ph_high": 8.4,
      "sal_low": 1.024,
      "sal_high": 1.026,
      "temp_low": 75,
      "temp_high": 80
    },
    "seasonal": null,
    "careLabel": "Intermediate",
    "visualCue": "Look for a laterally compressed body, pointed snout, and deliberate stop-start swimming.",
    "bestWith": [
      "Mature systems that meet the minimum tank size",
      "Tankmates chosen around its behavior and adult size",
      "Semi-aggressive tankmates of similar size"
    ],
    "cautionWith": [
      "Tankmates that do not match its adult size or activity level",
      "Corals or polyps that could be nipped or disturbed"
    ],
    "staffNote": "",
    "headerSummary": "Unusual display fish whose feeding behavior and compatibility need to be discussed first. Plan on roughly 30+ gal or larger long term.",
    "behavior": "Many filefish move in short deliberate bursts and can seem thoughtful or cautious rather than busy.",
    "feedingNotes": "Confirm what the individual is actually eating before the sale and support that routine at home rather than assuming any filefish takes anything. Catalog diet listing: Omnivore.",
    "buyingGuidance": "The right sale here is less about novelty and more about honest feeding history plus realistic compatibility expectations.",
    "recognitionNotes": "Look for the pointed snout and stop-start body posture that give filefish a distinctive silhouette."
  },
  {
    "id": "orange-spotted-filefish",
    "name": "Orange Spotted Filefish",
    "name_es": "Orange Spotted Filefish",
    "aliases": [],
    "scientific": "Oxymonacanthus longirostris",
    "category": "Other Fish",
    "type": "Saltwater Fish",
    "price": 0,
    "stockSize": "",
    "maxSize": "5 in",
    "minTank": "50+ gal",
    "diet": "Corallivore / specialist feeder",
    "diet_es": "",
    "origin": "Unknown",
    "origin_es": "",
    "habitat": "Reef / rocky",
    "tankCode": "",
    "aggression": 38,
    "coralRisk": 28,
    "invertRisk": 20,
    "careDifficulty": 42,
    "role": "Unusual display fish whose feeding behavior and compatibility need to be discussed first",
    "role_es": "",
    "overview": "Orange Spotted Filefish is an unusual display fish whose feeding habits and compatibility should be discussed honestly. The catalog lists a minimum tank around 50+ gal. Adult size is listed around 5 in. Diet here is listed as Corallivore / specialist feeder.",
    "overview_es": "",
    "facts": [
      "Adult size in this catalog is listed around 5 in.",
      "Plan around roughly 50+ gal or larger for long-term care.",
      "Diet in this catalog: Corallivore / specialist feeder."
    ],
    "photoTitle": "Orange Spotted Filefish",
    "inStock": false,
    "badges": [],
    "water": {
      "ph_low": 8,
      "ph_high": 8.4,
      "sal_low": 1.024,
      "sal_high": 1.026,
      "temp_low": 75,
      "temp_high": 80
    },
    "seasonal": null,
    "careLabel": "Intermediate",
    "visualCue": "Look for a laterally compressed body, pointed snout, and deliberate stop-start swimming.",
    "bestWith": [
      "Mature systems that meet the minimum tank size",
      "Tankmates chosen around its behavior and adult size",
      "Semi-aggressive tankmates of similar size"
    ],
    "cautionWith": [
      "Tankmates that do not match its adult size or activity level",
      "Corals or polyps that could be nipped or disturbed"
    ],
    "staffNote": "",
    "headerSummary": "Unusual display fish whose feeding behavior and compatibility need to be discussed first. Plan on roughly 50+ gal or larger long term.",
    "behavior": "Usually calm and deliberate, often working coral surfaces and structure rather than swimming openly.",
    "feedingNotes": "This is a specialty feeder and should only be sold when the buyer already knows how they will support it long term.",
    "recognitionNotes": "Long snout, orange spots, and bright blue-green patterning make it instantly different from the utility filefish.",
    "buyingGuidance": "A classic expert-only sale. Beauty alone is not a reason to take this fish home."
  },
  {
    "id": "sargassum-angler",
    "name": "Sargassum Angler",
    "name_es": "Sargassum Angler",
    "aliases": [],
    "scientific": "Histrio histrio",
    "category": "Other Fish",
    "type": "Saltwater Fish",
    "price": 0,
    "stockSize": "",
    "maxSize": "8 in",
    "minTank": "30+ gal",
    "diet": "Carnivore",
    "diet_es": "",
    "origin": "Unknown",
    "origin_es": "",
    "habitat": "Reef / rocky",
    "tankCode": "",
    "aggression": 38,
    "coralRisk": 28,
    "invertRisk": 20,
    "careDifficulty": 42,
    "role": "Ambush predator with specialist feeding and strong tankmate limitations",
    "role_es": "",
    "overview": "Sargassum Angler is a specialist ambush predator with serious tankmate and feeding limitations. The catalog lists a minimum tank around 30+ gal. Adult size is listed around 8 in. Diet here is listed as Carnivore.",
    "overview_es": "",
    "facts": [
      "Adult size in this catalog is listed around 8 in.",
      "Plan around roughly 30+ gal or larger for long-term care.",
      "Diet in this catalog: Carnivore."
    ],
    "photoTitle": "Sargassum Angler",
    "inStock": false,
    "badges": [],
    "water": {
      "ph_low": 8,
      "ph_high": 8.4,
      "sal_low": 1.024,
      "sal_high": 1.026,
      "temp_low": 75,
      "temp_high": 80
    },
    "seasonal": null,
    "careLabel": "Intermediate",
    "visualCue": "Look for a chunky ambush body with a huge mouth and a tendency to sit still between lunges.",
    "bestWith": [
      "Mature systems that meet the minimum tank size",
      "Tankmates chosen around its behavior and adult size",
      "Semi-aggressive tankmates of similar size"
    ],
    "cautionWith": [
      "Tankmates that do not match its adult size or activity level",
      "Corals or polyps that could be nipped or disturbed"
    ],
    "staffNote": "",
    "headerSummary": "Ambush predator with specialist feeding and strong tankmate limitations. Plan on roughly 30+ gal or larger long term.",
    "behavior": "Mostly still until it strikes. This is a wait-and-lunge predator, not an active display swimmer.",
    "feedingNotes": "Needs a meaty carnivore routine and careful compatibility planning so tankmates do not become meals.",
    "recognitionNotes": "The lure and body shape give it away once you know to look for an anglerfish silhouette.",
    "buyingGuidance": "Sell to oddball keepers who specifically want angler behavior and understand the prey risk."
  },
  {
    "id": "tassled-filefish",
    "name": "Tassled Filefish",
    "name_es": "Tassled Filefish",
    "aliases": [],
    "scientific": "Chaetodermis penicilligerus",
    "category": "Other Fish",
    "type": "Saltwater Fish",
    "price": 0,
    "stockSize": "",
    "maxSize": "12 in",
    "minTank": "75+ gal",
    "diet": "Omnivore",
    "diet_es": "",
    "origin": "Unknown",
    "origin_es": "",
    "habitat": "Reef / rocky",
    "tankCode": "",
    "aggression": 38,
    "coralRisk": 28,
    "invertRisk": 20,
    "careDifficulty": 42,
    "role": "Unusual display fish whose feeding behavior and compatibility need to be discussed first",
    "role_es": "",
    "overview": "Tassled Filefish is an unusual display fish whose feeding habits and compatibility should be discussed honestly. The catalog lists a minimum tank around 75+ gal. Adult size is listed around 12 in. Diet here is listed as Omnivore.",
    "overview_es": "",
    "facts": [
      "Adult size in this catalog is listed around 12 in.",
      "Plan around roughly 75+ gal or larger for long-term care.",
      "Diet in this catalog: Omnivore."
    ],
    "photoTitle": "Tassled Filefish",
    "inStock": false,
    "badges": [],
    "water": {
      "ph_low": 8,
      "ph_high": 8.4,
      "sal_low": 1.024,
      "sal_high": 1.026,
      "temp_low": 75,
      "temp_high": 80
    },
    "seasonal": null,
    "careLabel": "Intermediate",
    "visualCue": "Look for a laterally compressed body, pointed snout, and deliberate stop-start swimming.",
    "bestWith": [
      "Mature systems that meet the minimum tank size",
      "Tankmates chosen around its behavior and adult size",
      "Semi-aggressive tankmates of similar size"
    ],
    "cautionWith": [
      "Tankmates that do not match its adult size or activity level",
      "Corals or polyps that could be nipped or disturbed"
    ],
    "staffNote": "",
    "headerSummary": "Unusual display fish whose feeding behavior and compatibility need to be discussed first. Plan on roughly 75+ gal or larger long term.",
    "behavior": "Usually calm and oddball rather than fast or aggressive, but can still make a reef keeper nervous if it starts tasting corals.",
    "feedingNotes": "Feed a varied omnivore routine with both meaty and plant-inclusive prepared foods.",
    "recognitionNotes": "The fuzzy tassel-like body surface makes it stand out immediately.",
    "buyingGuidance": "Best sold to buyers who want an unusual fish and are realistic about reef risk rather than assuming total coral safety."
  },
  {
    "id": "wartskin-angler",
    "name": "Wartskin Angler",
    "name_es": "Wartskin Angler",
    "aliases": [],
    "scientific": "Antennarius maculatus",
    "category": "Other Fish",
    "type": "Saltwater Fish",
    "price": 0,
    "stockSize": "",
    "maxSize": "4 in",
    "minTank": "30+ gal",
    "diet": "Carnivore",
    "diet_es": "",
    "origin": "Unknown",
    "origin_es": "",
    "habitat": "Reef / rocky",
    "tankCode": "",
    "aggression": 38,
    "coralRisk": 28,
    "invertRisk": 20,
    "careDifficulty": 42,
    "role": "Ambush predator with specialist feeding and strong tankmate limitations",
    "role_es": "",
    "overview": "Wartskin Angler is a specialist ambush predator with serious tankmate and feeding limitations. The catalog lists a minimum tank around 30+ gal. Adult size is listed around 4 in. Diet here is listed as Carnivore.",
    "overview_es": "",
    "facts": [
      "Adult size in this catalog is listed around 4 in.",
      "Plan around roughly 30+ gal or larger for long-term care.",
      "Diet in this catalog: Carnivore."
    ],
    "photoTitle": "Wartskin Angler",
    "inStock": false,
    "badges": [],
    "water": {
      "ph_low": 8,
      "ph_high": 8.4,
      "sal_low": 1.024,
      "sal_high": 1.026,
      "temp_low": 75,
      "temp_high": 80
    },
    "seasonal": null,
    "careLabel": "Intermediate",
    "visualCue": "Look for a chunky ambush body with a huge mouth and a tendency to sit still between lunges.",
    "bestWith": [
      "Mature systems that meet the minimum tank size",
      "Tankmates chosen around its behavior and adult size",
      "Semi-aggressive tankmates of similar size"
    ],
    "cautionWith": [
      "Tankmates that do not match its adult size or activity level",
      "Corals or polyps that could be nipped or disturbed"
    ],
    "staffNote": "",
    "headerSummary": "Ambush predator with specialist feeding and strong tankmate limitations. Plan on roughly 30+ gal or larger long term.",
    "behavior": "Perches, blends in, and then strikes explosively. Activity is low until prey or food appears.",
    "feedingNotes": "Feed meaty carnivore foods and build the stocking plan around what this fish can swallow over time.",
    "recognitionNotes": "The lumpy body and frogfish stance are the giveaway.",
    "buyingGuidance": "Great for buyers who specifically want frogfish behavior, wrong for anyone building a traditional peaceful reef."
  },
  {
    "id": "cuban-hogfish",
    "name": "Cuban Hogfish",
    "name_es": "Cuban Hogfish",
    "aliases": [],
    "scientific": "Bodianus pulchellus",
    "category": "Other Fish",
    "type": "Saltwater Fish",
    "price": 0,
    "stockSize": "",
    "maxSize": "12 in",
    "minTank": "75+ gal",
    "diet": "Carnivore",
    "diet_es": "",
    "origin": "Unknown",
    "origin_es": "",
    "habitat": "Reef / rocky",
    "tankCode": "",
    "aggression": 38,
    "coralRisk": 28,
    "invertRisk": 20,
    "careDifficulty": 56,
    "role": "Active, assertive fish that blends wrasse-like motion with a more robust build",
    "role_es": "",
    "overview": "Cuban Hogfish is an active robust fish that brings motion and personality but needs compatible tankmates. The catalog lists a minimum tank around 75+ gal. Adult size is listed around 12 in. Diet here is listed as Carnivore.",
    "overview_es": "",
    "facts": [
      "Adult size in this catalog is listed around 12 in.",
      "Plan around roughly 75+ gal or larger for long-term care.",
      "Diet in this catalog: Carnivore."
    ],
    "photoTitle": "Cuban Hogfish",
    "inStock": false,
    "badges": [],
    "water": {
      "ph_low": 8,
      "ph_high": 8.4,
      "sal_low": 1.024,
      "sal_high": 1.026,
      "temp_low": 75,
      "temp_high": 80
    },
    "seasonal": null,
    "careLabel": "Intermediate",
    "visualCue": "Look for a longer wrasse-like body with a thicker head and more robust build.",
    "bestWith": [
      "Mature systems that meet the minimum tank size",
      "Tankmates chosen around its behavior and adult size",
      "Semi-aggressive tankmates of similar size"
    ],
    "cautionWith": [
      "Tankmates that do not match its adult size or activity level",
      "Corals or polyps that could be nipped or disturbed"
    ],
    "staffNote": "",
    "headerSummary": "Active, assertive fish that blends wrasse-like motion with a more robust build. Plan on roughly 75+ gal or larger long term.",
    "behavior": "Constant swimmer that uses the whole tank and does better with room than cramped mixed communities.",
    "feedingNotes": "Offer a varied meaty diet and plan around a fish that stays active throughout the day.",
    "recognitionNotes": "Longer hogfish profile and constant cruising separate it from perch-and-wait predators.",
    "buyingGuidance": "A strong sale for buyers who want movement and personality, provided their tankmates and inverts fit the plan."
  },
  {
    "id": "miniatus-grouper",
    "name": "Miniatus Grouper",
    "name_es": "Miniatus Grouper",
    "aliases": [],
    "scientific": "Cephalopholis miniata",
    "category": "Other Fish",
    "type": "Saltwater Fish",
    "price": 0,
    "stockSize": "",
    "maxSize": "18 in",
    "minTank": "180+ gal",
    "diet": "Carnivore",
    "diet_es": "",
    "origin": "Unknown",
    "origin_es": "",
    "habitat": "Reef / rocky",
    "tankCode": "",
    "aggression": 38,
    "coralRisk": 28,
    "invertRisk": 20,
    "careDifficulty": 56,
    "role": "Juvenile display predator that needs honest discussion about long-term size",
    "role_es": "",
    "overview": "Miniatus Grouper is a juvenile-friendly predator sale that still needs honest discussion about long-term size and appetite. The catalog lists a minimum tank around 180+ gal. Adult size is listed around 18 in. Diet here is listed as Carnivore.",
    "overview_es": "",
    "facts": [
      "Adult size in this catalog is listed around 18 in.",
      "Plan around roughly 180+ gal or larger for long-term care.",
      "Diet in this catalog: Carnivore."
    ],
    "photoTitle": "Miniatus Grouper",
    "inStock": false,
    "badges": [],
    "water": {
      "ph_low": 8,
      "ph_high": 8.4,
      "sal_low": 1.024,
      "sal_high": 1.026,
      "temp_low": 75,
      "temp_high": 80
    },
    "seasonal": null,
    "careLabel": "Intermediate",
    "visualCue": "Look for a heavier-bodied predator with a broad mouth and steady, confident cruising.",
    "bestWith": [
      "Mature systems that meet the minimum tank size",
      "Tankmates chosen around its behavior and adult size",
      "Semi-aggressive tankmates of similar size"
    ],
    "cautionWith": [
      "Tankmates that do not match its adult size or activity level",
      "Corals or polyps that could be nipped or disturbed"
    ],
    "staffNote": "",
    "headerSummary": "Juvenile display predator that needs honest discussion about long-term size. Plan on roughly 180+ gal or larger long term.",
    "behavior": "Confident and food-driven, often shifting from hover to explosive feeding response very quickly.",
    "feedingNotes": "Feed a robust carnivore diet sized for a true predator and plan around the waste and adult bulk that come with it.",
    "recognitionNotes": "Thick grouper build and obvious predator mouth make the role clear instantly.",
    "buyingGuidance": "Sell as a predator-system fish only. The right buyer already expects large prey-focused behavior and heavy bioload."
  },
  {
    "id": "panther-grouper",
    "name": "Panther Grouper",
    "name_es": "Panther Grouper",
    "aliases": [],
    "scientific": "Cromileptes altivelis",
    "category": "Other Fish",
    "type": "Saltwater Fish",
    "price": 0,
    "stockSize": "",
    "maxSize": "28 in",
    "minTank": "300+ gal",
    "diet": "Carnivore",
    "diet_es": "Carnívoro",
    "origin": "Western Pacific",
    "origin_es": "Pacífico Occidental",
    "habitat": "Coral reefs",
    "tankCode": "",
    "aggression": 55,
    "coralRisk": 15,
    "invertRisk": 70,
    "careDifficulty": 35,
    "role": "Spotted grouper that looks cute small but grows huge",
    "role_es": "Mero moteado que se ve lindo pequeño pero crece enorme",
    "overview": "Juveniles are adorable with white body covered in black polka dots and a comically upturned face. But they grow to over 2 feet and will eat anything that fits in their mouth.",
    "overview_es": "Los juveniles son adorables con cuerpo blanco cubierto de lunares negros. Pero crecen más de 60cm y comerán todo lo que quepa en su boca.",
    "facts": [
      "Adult size in this catalog is listed around 28 in.",
      "Plan around roughly 300+ gal or larger for long-term care.",
      "Diet in this catalog: Carnivore."
    ],
    "photoTitle": "Cromileptes_altivelis",
    "inStock": false,
    "badges": [],
    "water": {
      "ph_low": 8,
      "ph_high": 8.4,
      "sal_low": 1.024,
      "sal_high": 1.026,
      "temp_low": 75,
      "temp_high": 80
    },
    "seasonal": null,
    "careLabel": "Moderate",
    "visualCue": "Look for a heavier-bodied predator with a broad mouth and steady, confident cruising.",
    "bestWith": [
      "Mature systems that meet the minimum tank size",
      "Reef-safe community plans with compatible tankmates",
      "Semi-aggressive tankmates of similar size"
    ],
    "cautionWith": [
      "Tankmates that do not match its adult size or activity level",
      "Shrimp, snails, crabs, or other ornamental invertebrates",
      "Systems smaller than 300+ gal"
    ],
    "staffNote": "",
    "headerSummary": "Spotted grouper that looks cute small but grows huge. Plan on roughly 300+ gal or larger long term.",
    "behavior": "Predatory and eventually imposing, with a huge mouth and a strong ability to reframe tankmate choices as prey choices.",
    "feedingNotes": "Use a serious carnivore feeding plan and expect the system to scale around this fish, not the other way around.",
    "recognitionNotes": "The spotted juvenile pattern is famous, but it should always be discussed alongside the adult size.",
    "buyingGuidance": "Only for buyers who fully understand the adult fish. This is not an average-store predator add-on."
  },
  {
    "id": "porkfish",
    "name": "Porkfish",
    "name_es": "Porkfish",
    "aliases": [],
    "scientific": "Anisotremus virginicus",
    "category": "Other Fish",
    "type": "Saltwater Fish",
    "price": 0,
    "stockSize": "",
    "maxSize": "16 in",
    "minTank": "125+ gal",
    "diet": "Carnivore / omnivore",
    "diet_es": "",
    "origin": "Unknown",
    "origin_es": "",
    "habitat": "Reef / rocky",
    "tankCode": "",
    "aggression": 38,
    "coralRisk": 28,
    "invertRisk": 20,
    "careDifficulty": 56,
    "role": "Marine fish profile that should be matched to tank size, diet, and temperament",
    "role_es": "",
    "overview": "Porkfish should be matched to the buyer based on space, diet, and compatibility rather than impulse color alone. The catalog lists a minimum tank around 125+ gal. Adult size is listed around 16 in. Diet here is listed as Carnivore / omnivore.",
    "overview_es": "",
    "facts": [
      "Adult size in this catalog is listed around 16 in.",
      "Plan around roughly 125+ gal or larger for long-term care.",
      "Diet in this catalog: Carnivore / omnivore."
    ],
    "photoTitle": "Porkfish",
    "inStock": false,
    "badges": [],
    "water": {
      "ph_low": 8,
      "ph_high": 8.4,
      "sal_low": 1.024,
      "sal_high": 1.026,
      "temp_low": 75,
      "temp_high": 80
    },
    "seasonal": null,
    "careLabel": "Intermediate",
    "visualCue": "Use the overall body shape, swimming style, and color pattern together with the label rather than relying on one feature alone.",
    "bestWith": [
      "Mature systems that meet the minimum tank size",
      "Tankmates chosen around its behavior and adult size",
      "Semi-aggressive tankmates of similar size"
    ],
    "cautionWith": [
      "Tankmates that do not match its adult size or activity level",
      "Corals or polyps that could be nipped or disturbed"
    ],
    "staffNote": "",
    "headerSummary": "Marine fish profile that should be matched to tank size, diet, and temperament. Plan on roughly 125+ gal or larger long term.",
    "behavior": "Active swimmer that wants room and looks best when not cramped into undersized rock-heavy layouts.",
    "feedingNotes": "Feed a varied meaty/omnivore routine and size the system around adult swimming space.",
    "recognitionNotes": "Grunt-like body shape and striped yellow-silver appearance help it stand out from reef-community fish.",
    "buyingGuidance": "Best sold to buyers with room for a larger active display fish, not someone trying to squeeze one more fish into a mixed reef."
  },
  {
    "id": "coral-catshark",
    "name": "Coral Catshark",
    "name_es": "Tiburón Gato de Coral",
    "scientific": "Atelomycterus marmoratus",
    "category": "Other Fish",
    "type": "Saltwater Fish",
    "aggression": 30,
    "coralRisk": 5,
    "invertRisk": 60,
    "careDifficulty": 65,
    "diet": "Carnivore",
    "diet_es": "Carnívoro",
    "origin": "Indo-Pacific",
    "origin_es": "Indo-Pacífico",
    "habitat": "Coral reefs",
    "maxSize": "28 in",
    "minTank": "300+ gal",
    "photoTitle": "Atelomycterus_marmoratus",
    "role": "Small marbled shark for very large systems",
    "role_es": "Tiburón marmoleado para sistemas muy grandes",
    "overview": "Beautiful small shark with marbled pattern. Nocturnal and relatively docile but needs extremely large system.",
    "overview_es": "Hermoso tiburón pequeño con patrón marmoleado. Nocturno pero necesita sistema extremadamente grande.",
    "inStock": false,
    "price": 0,
    "stockSize": "",
    "tankCode": "",
    "badges": [],
    "aliases": [],
    "facts": [
      "Minimum suggested system is 300+ gal.",
      "Diet profile: Carnivore. Feeding should match that long-term, not just what it accepts in the store.",
      "Compatibility snapshot: reef safe, high invert risk, and temperament trends moderate."
    ],
    "water": {
      "ph": [
        8,
        8.4
      ],
      "salinity": [
        1.023,
        1.026
      ],
      "temp": [
        75,
        80
      ],
      "ph_low": null,
      "ph_high": null,
      "sal_low": null,
      "sal_high": null,
      "temp_low": null,
      "temp_high": null
    },
    "seasonal": null,
    "careLabel": "Advanced",
    "visualCue": "Use the overall body shape, swimming style, and color pattern together with the label rather than relying on one feature alone.",
    "bestWith": [
      "Mature systems that meet the minimum tank size",
      "Reef-safe community plans with compatible tankmates",
      "Semi-aggressive tankmates of similar size"
    ],
    "cautionWith": [
      "Tankmates that do not match its adult size or activity level",
      "Shrimp, snails, crabs, or other ornamental invertebrates",
      "Immature tanks or buyers without a long-term care plan"
    ],
    "staffNote": "",
    "headerSummary": "Small marbled shark for very large systems. Use the overall body shape, swimming style, and color pattern together with the label rather than relying on one feature alone. Plan on at least 300+ gal.",
    "behavior": "Bottom-oriented and generally calm, but highly specialized in husbandry compared with typical marine fish.",
    "feedingNotes": "Needs a serious carnivore routine and a system layout that avoids abrasion, stress, and temperature mistakes.",
    "recognitionNotes": "Classic small catshark shape and bottom-resting behavior separate it immediately from fish profiles.",
    "buyingGuidance": "Only for buyers already prepared for shark-specific care. This is not just a big fish with a cooler body shape."
  }
];
